using UnityEngine;

namespace Konoha.Campaign
{
    // Scene-side description of the Jalur Takhta slice: objective transforms, checkpoint
    // respawn points and enemy placements. Generated by CampaignPreviewProject; read by
    // the director (server) and the HUD (every peer). Points lie on the collision-tested
    // campaign route (CampaignPreviewSceneTests) so nobody spawns inside geometry.
    public sealed class CampaignStage : MonoBehaviour
    {
        public Transform plaza;
        public Transform majelis;
        public Transform biro;
        public Transform garda;
        public Transform chair;

        // 0.0.9.1 route map (see CampaignCapitalArt): spawn in the south, seat on the north terrace.
        public Vector3 startPoint = new Vector3(0f, 0.1f, -44f);
        // Checkpoint 5: just inside the Gerbang Dalam, outside the Garda aggro/leash rings,
        // so a revived hero is not attacked while standing still.
        // 0.1.0: 18.5 keeps a revived hero clear of the Garda LOCKDOWN ring (radius 8.5 around z 28).
        public Vector3 gardaCheckpoint = new Vector3(0f, 0.1f, 18.5f);
        public Vector3[] gateSpawnPoints =
        {
            new Vector3(-2f, 0.1f, -30f),
            new Vector3(0f, 0.1f, -28.5f),
            new Vector3(2f, 0.1f, -30f)
        };
        // Order follows EncounterComposer.Compose(GardaTakhta, 1): Panglima, then the Pengawal.
        public Vector3[] gardaSpawnPoints =
        {
            new Vector3(0f, 0.1f, 30f),
            new Vector3(3.5f, 0.1f, 28f),
            new Vector3(-3.5f, 0.1f, 28f)
        };
        // §8.3 bala bantuan when the Panglima drops below 50% Wibawa.
        public Vector3[] gardaReinforcePoints =
        {
            new Vector3(-4f, 0.1f, 26f),
            new Vector3(4f, 0.1f, 26f)
        };
        // §9 counterattack waves gather at the foot of the ramp and climb to the seat.
        public Vector3[] counterattackSpawnPoints =
        {
            new Vector3(-6f, 0.1f, 30f),
            new Vector3(6f, 0.1f, 30f),
            new Vector3(0f, 0.1f, 25.5f)
        };
        // Where DUDUK places the hero: just in front of the seat, facing the ramp.
        public Vector3 seatOffset = new Vector3(0f, 0.3f, -1.3f);

        // 0.0.9.2 Majelis Daun sidang in front of its hall (x -28). Order follows
        // EncounterComposer.Compose(MajelisDaun, 1): Ketua, 2 Senior, 3 Staf Fraksi, Pengawal.
        // All stay south of z -4.2, clear of the hall steps (z -3.15 .. -2.3).
        public Vector3[] majelisSpawnPoints =
        {
            new Vector3(-30f, 0.1f, -5.5f),
            new Vector3(-27f, 0.1f, -7.8f),
            new Vector3(-26.5f, 0.1f, -4.3f),
            new Vector3(-28.5f, 0.1f, -9f),
            new Vector3(-25f, 0.1f, -9.5f),
            new Vector3(-31.5f, 0.1f, -8f),
            new Vector3(-24f, 0.1f, -6f)
        };
        // 0.0.9.3 Biro Prosedur loket hall (east wing, south of the hall at x 28). The
        // Kepala Biro waits in a walled office in front of the hall until all lokets are
        // stamped. Values match CampaignCapitalArt (booths, office walls, zone discs).
        public Vector3[] loketPoints =
        {
            new Vector3(22.5f, 0.1f, -9f),
            new Vector3(27.5f, 0.1f, -10.5f),
            new Vector3(32f, 0.1f, -8.5f)
        };
        public Vector3 biroOfficeCenter = new Vector3(28f, 0.1f, -4.8f);
        // Office walls (x 25..31, z -6.6..-1.8) with a single door in the south wall at x 28.
        public Vector2 officeMin = new Vector2(25f, -6.6f);
        public Vector2 officeMax = new Vector2(31f, -1.8f);
        public Vector3 officeDoorInside = new Vector3(28f, 0.1f, -5.6f);
        public Vector3 officeDoorOutside = new Vector3(28f, 0.1f, -7.6f);
        public Vector3 biroLeaderPoint = new Vector3(28f, 0.1f, -4.6f);
        public Vector3 biroSpecialistPoint = new Vector3(30f, 0.1f, -14.5f);
        public Vector3 biroGuardPoint = new Vector3(24f, 0.1f, -7.2f);
        public Vector3[] biroArsipPoints =
        {
            new Vector3(25f, 0.1f, -13.8f),
            new Vector3(31.2f, 0.1f, -12.8f)
        };

        // Index of the loket zone containing this point, -1 when none.
        public int LoketAt(Vector3 position)
        {
            for (int i = 0; i < loketPoints.Length; i++)
                if (CampaignObjectiveDirector.Near(position, loketPoints[i], CampaignTuning.Biro.LoketRadius))
                    return i;
            return -1;
        }

        // Checkpoints 3/4 sit on the wing corridor, outside the sector leash (11 m), so a
        // revived hero is not dropped into the middle of the sidang.
        public Vector3 majelisCheckpoint = new Vector3(-14f, 0.1f, -5f);
        public Vector3 biroCheckpoint = new Vector3(14f, 0.1f, -5f);

        // Walkable connections for enemy steering (no navmesh): the throne terrace is
        // reached only by its ramp, the north only through the Gerbang Dalam.
        public float terraceHeight = 5f;
        public Vector3 rampBase = new Vector3(0f, 0f, 30f);
        public Vector3 rampTop = new Vector3(0f, 5f, 43f);
        public float rampHalfWidth = 3.4f;
        public float innerGateZ = 17f;
        public float innerGateHalfWidth = 2.4f;

        // Characters are dropped slightly above the floor and settle with gravity.
        public const float DropHeight = 0.25f;

        public CampaignObjectiveLayout Layout => new CampaignObjectiveLayout(
            plaza.position, majelis.position, biro.position, garda.position, chair.position);

        public Vector3 CheckpointPosition(CampaignCheckpoint checkpoint)
        {
            Vector3 point;
            switch (checkpoint)
            {
                case CampaignCheckpoint.PlazaAspirasi: point = plaza.position; break;
                case CampaignCheckpoint.MajelisDaun: point = majelisCheckpoint; break;
                case CampaignCheckpoint.BiroProsedur: point = biroCheckpoint; break;
                case CampaignCheckpoint.GardaTakhta: point = gardaCheckpoint; break;
                default: point = startPoint; break;
            }
            return new Vector3(point.x, Mathf.Max(point.y, 0f) + DropHeight, point.z);
        }

        public bool InOffice(Vector3 point) =>
            point.x > officeMin.x && point.x < officeMax.x && point.z > officeMin.y && point.z < officeMax.y;

        // Next intermediate point on the way from 'from' to 'to'; 'to' itself when direct.
        public Vector3 Steer(Vector3 from, Vector3 to)
        {
            // The Kepala Biro office is entered and left only through its door.
            bool fromOffice = InOffice(from);
            if (fromOffice != InOffice(to))
            {
                Vector3 near = fromOffice ? officeDoorInside : officeDoorOutside;
                Vector3 far = fromOffice ? officeDoorOutside : officeDoorInside;
                bool inDoorway = Mathf.Abs(from.x - near.x) < 0.9f &&
                    from.z >= Mathf.Min(near.z, far.z) - 0.4f && from.z <= Mathf.Max(near.z, far.z) + 0.4f;
                Vector3 next = inDoorway ? far : near;
                return new Vector3(next.x, from.y, next.z);
            }

            float level = terraceHeight - 1f;
            bool fromHigh = from.y > level;
            bool toHigh = to.y > level;
            if (fromHigh != toHigh)
            {
                bool inRampLane = Mathf.Abs(from.x - rampBase.x) < rampHalfWidth &&
                    from.z > rampBase.z - 0.5f && from.z < rampTop.z + 0.5f;
                if (toHigh)
                    return inRampLane || FlatDistance(from, rampBase) < 1f ? rampTop : rampBase;
                return inRampLane || FlatDistance(from, rampTop) < 1f ? rampBase : rampTop;
            }

            bool fromNorth = from.z > innerGateZ;
            bool toNorth = to.z > innerGateZ;
            if (!fromHigh && fromNorth != toNorth)
            {
                bool inGateway = Mathf.Abs(from.x) < innerGateHalfWidth && Mathf.Abs(from.z - innerGateZ) < 2.2f;
                if (!inGateway)
                    return new Vector3(0f, from.y, innerGateZ + (fromNorth ? 2f : -2f));
            }
            return to;
        }

        private static float FlatDistance(Vector3 a, Vector3 b)
        {
            float x = a.x - b.x;
            float z = a.z - b.z;
            return Mathf.Sqrt(x * x + z * z);
        }

        public static Quaternion Facing(Vector3 from, Vector3 to)
        {
            Vector3 direction = to - from;
            direction.y = 0f;
            return direction.sqrMagnitude > 0.001f ? Quaternion.LookRotation(direction.normalized) : Quaternion.identity;
        }
    }
}
