using UnityEngine;

namespace Konoha.Campaign
{
    // Scene-side description of the Jalur Takhta slice: objective transforms, checkpoint
    // respawn points and enemy placements. Generated by CampaignPreviewProject; read by
    // the director (server) and the HUD (every peer). Points lie on the collision-tested
    // campaign route (CampaignPreviewSceneTests) so nobody spawns inside geometry.
    public sealed class CampaignStage : MonoBehaviour
    {
        public Transform plaza;
        public Transform majelis;
        public Transform biro;
        public Transform garda;
        public Transform chair;

        public Vector3 startPoint = new Vector3(0f, 0.1f, -9f);
        // Checkpoint 5 sits outside the Garda aggro/leash rings so a revived hero is not
        // attacked while standing still.
        public Vector3 gardaCheckpoint = new Vector3(4.4f, 0.1f, -2f);
        public Vector3[] gateSpawnPoints =
        {
            new Vector3(0.6f, 0.1f, -3.3f),
            new Vector3(2.2f, 0.1f, -3.3f),
            new Vector3(3.8f, 0.1f, -3.3f)
        };
        public Vector3[] gardaSpawnPoints =
        {
            new Vector3(0f, 0.1f, 7.4f),
            new Vector3(2.2f, 0.1f, 7.4f)
        };
        public Vector3 counterattackSpawnPoint = new Vector3(4.4f, 0.1f, 7.4f);

        // Characters are dropped slightly above the floor and settle with gravity.
        public const float DropHeight = 0.25f;

        public CampaignObjectiveLayout Layout => new CampaignObjectiveLayout(
            plaza.position, majelis.position, biro.position, garda.position, chair.position);

        public Vector3 CheckpointPosition(CampaignCheckpoint checkpoint)
        {
            Vector3 point;
            switch (checkpoint)
            {
                case CampaignCheckpoint.PlazaAspirasi: point = plaza.position; break;
                case CampaignCheckpoint.MajelisDaun: point = majelis.position; break;
                case CampaignCheckpoint.BiroProsedur: point = biro.position; break;
                case CampaignCheckpoint.GardaTakhta: point = gardaCheckpoint; break;
                default: point = startPoint; break;
            }
            return new Vector3(point.x, Mathf.Max(point.y, 0f) + DropHeight, point.z);
        }

        public static Quaternion Facing(Vector3 from, Vector3 to)
        {
            Vector3 direction = to - from;
            direction.y = 0f;
            return direction.sqrMagnitude > 0.001f ? Quaternion.LookRotation(direction.normalized) : Quaternion.identity;
        }
    }
}
