using System;
using System.Globalization;
using System.Text;

namespace Konoha.Campaign
{
    // 0.6.0 KARIER Level 1 "Warga Biasa" (Docs/VISI_KONOHA_HIDUP_v3.md §3): the life of an
    // ordinary Konoha citizen who wants to become Ketua RT. Plain C# (EditMode tested): the
    // scene side (KarierController) feeds the hero position and the fight state and shows
    // the results. Money must be earned first; dirty money is fast but leaves a record.

    // Ground position (x, z) without UnityEngine.
    public struct KarierPoint
    {
        public readonly float X, Z;

        public KarierPoint(float x, float z)
        {
            X = x;
            Z = z;
        }

        public static float Distance(KarierPoint a, KarierPoint b)
        {
            float dx = a.X - b.X, dz = a.Z - b.Z;
            return (float)Math.Sqrt(dx * dx + dz * dz);
        }

        public static bool Near(KarierPoint a, KarierPoint b, float radius) => Distance(a, b) <= radius;
    }

    // Where things happen in the city (generated by CampaignPreviewProject).
    public sealed class KarierLayout
    {
        public string[] PlaceNames = new string[0];
        public KarierPoint[] Places = new KarierPoint[0];
        public KarierPoint KuliPickup, KuliDrop, Warkop, PosRt;
        // 0.6.1: jajan stalls and rentals.
        public KarierPoint Siomay, Salome, Bakso, SewaSepeda, SewaMotor;
        public string[] SapaNames = new string[0];
        public KarierPoint[] SapaPoints = new KarierPoint[0];
    }

    public enum KarierJob { None, Ojol, Kuli, Buzzer }

    public enum KarierStep { None, OjolJemput, OjolAntar, KuliAmbil, KuliAntar, BuzzerKetik }

    public enum KarierPoliceReason { None, Keributan, Hoaks }

    public enum KarierPoliceChoice { Kabur, Damai, Polsek, Saksi }

    public enum KarierCue { Notif, Koin, Gagal, Teriak, Melerai, Sirene, Restu, Daftar, Misi }

    public enum KarierAction { None, Makan, Sapa, DaftarRT, BeliSiomay, BeliSalome, BeliBakso, SewaSepeda, SewaMotor, Turun }

    public enum KarierRide { None, Sepeda, Motor }

    // The player's own citizen (character creator). Indices pick from the name lists.
    public struct KarierAvatar
    {
        public static readonly string[] SkinNames = { "LANGSAT", "SAWO MATANG", "SAWO GELAP", "KUNING LANGSAT" };
        public static readonly string[] HairNames = { "RAMBUT PENDEK", "RAMBUT PANJANG", "PECI", "JILBAB", "TOPI" };
        public static readonly string[] BodyNames = { "KURUS", "SEDANG", "BERISI" };
        public static readonly string[] ShirtNames = { "PUTIH", "HITAM", "MERAH", "BIRU", "HIJAU", "KUNING", "ABU-ABU" };
        public const int MaxNameLength = 14;

        public string Name;
        public bool Female;
        public int Skin, Hair, Body, Shirt;

        public static KarierAvatar Default => new KarierAvatar { Name = "WARGA", Female = false, Skin = 1, Hair = 0, Body = 1, Shirt = 0 };

        public KarierAvatar Clamped()
        {
            KarierAvatar result = this;
            result.Name = CleanName(Name);
            result.Skin = Wrap(Skin, SkinNames.Length);
            result.Hair = Wrap(Hair, HairNames.Length);
            result.Body = Wrap(Body, BodyNames.Length);
            result.Shirt = Wrap(Shirt, ShirtNames.Length);
            return result;
        }

        public static int Wrap(int value, int count) => count <= 0 ? 0 : ((value % count) + count) % count;

        // Upper case letters, digits and spaces, at most 14 characters; never empty.
        public static string CleanName(string raw)
        {
            if (string.IsNullOrEmpty(raw))
                return "WARGA";
            var builder = new StringBuilder(MaxNameLength);
            foreach (char c in raw.ToUpperInvariant())
            {
                if (builder.Length >= MaxNameLength)
                    break;
                if ((c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || (c == ' ' && builder.Length > 0))
                    builder.Append(c);
            }
            string name = builder.ToString().Trim();
            return name.Length == 0 ? "WARGA" : name;
        }

        public string Serialize()
        {
            KarierAvatar a = Clamped();
            return "A1;" + a.Name + ";" + (a.Female ? 1 : 0) + ";" + a.Skin + ";" + a.Hair + ";" + a.Body + ";" + a.Shirt;
        }

        public static bool TryParse(string text, out KarierAvatar avatar)
        {
            avatar = Default;
            if (string.IsNullOrEmpty(text))
                return false;
            string[] parts = text.Split(';');
            if (parts.Length != 7 || parts[0] != "A1")
                return false;
            if (!Int(parts[2], out int female) || !Int(parts[3], out int skin) || !Int(parts[4], out int hair) ||
                !Int(parts[5], out int body) || !Int(parts[6], out int shirt))
                return false;
            avatar = new KarierAvatar { Name = parts[1], Female = female == 1, Skin = skin, Hair = hair, Body = body, Shirt = shirt }.Clamped();
            return true;
        }

        internal static bool Int(string text, out int value) =>
            int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
    }

    public sealed class KarierLife
    {
        public event Action<string> Notified;
        public event Action<KarierCue> Cued;

        private readonly KarierLayout layout;
        private readonly Random random;
        private float energiCarry;

        public KarierLife(KarierLayout layout, int seed = 603)
        {
            this.layout = layout ?? new KarierLayout();
            random = new Random(seed);
            ResetProgress();
        }

        // --- Resources (saved) ----------------------------------------------------------
        public int Duit { get; private set; }
        public int Energi { get; private set; }
        public int Restu { get; private set; }
        public int CatatanHitam { get; private set; }
        public int SapaMask { get; private set; }
        public bool Registered { get; private set; }
        public int TripsOjol { get; private set; }
        public int SetKuli { get; private set; }
        public int PostBuzzer { get; private set; }
        public int PremanBeaten { get; private set; }
        public int FoodBought { get; private set; }
        public int RideCount { get; private set; }
        // 0.6.1 missions (index into Missions; Missions.Length = all done).
        public int Mission { get; private set; }
        public bool OfferPending => Mission == MisiTawaran;

        // --- Current activity (not saved) -------------------------------------------------
        public KarierJob Job { get; private set; }
        public KarierStep Step { get; private set; }
        public float StepProgress { get; private set; }
        public int OjolFrom { get; private set; } = -1;
        public int OjolTo { get; private set; } = -1;
        public float OjolTimeLeft { get; private set; }
        public float OjolTimeLimit { get; private set; }
        public int KuliDelivered { get; private set; }
        public bool Carrying { get; private set; }
        public float BuzzerCooldown { get; private set; }
        public float RebahanLeft { get; private set; }
        public bool Rebahan => RebahanLeft > 0f;
        public KarierRide Ride { get; private set; }
        public float EatLeft { get; private set; }
        public bool Eating => EatLeft > 0f;
        public float JailLeft { get; private set; }
        public bool InJail => JailLeft > 0f;

        // --- Keributan and police -------------------------------------------------------
        public float Keributan { get; private set; }
        public bool Shouted { get; private set; }
        public bool MeleraiDone { get; private set; }
        public float CalmLeft { get; private set; }
        public bool MeleraiActive => CalmLeft > 0f;
        public KarierPoliceReason PoliceReason { get; private set; }
        public bool PoliceArrived { get; private set; }
        public bool PoliceCalled => PoliceReason != KarierPoliceReason.None;
        // 0.6.1: seconds until the police arrive after warga shouted (-1 = not on the way).
        public float PoliceEta { get; private set; } = -1f;
        public bool BeatenThisFight { get; private set; }
        public bool CanSaksi => PoliceReason == KarierPoliceReason.Keributan && BeatenThisFight &&
            Restu >= CampaignTuning.Karier.SaksiRestu;
        public int TebusPrice => CampaignTuning.Karier.TebusBase + CatatanHitam * CampaignTuning.Karier.TebusPerCatatan;

        public KarierLayout Layout => layout;
        public bool CanDaftar => !Registered && Duit >= CampaignTuning.Karier.SyukuranRT && Restu >= CampaignTuning.Karier.RestuSyaratRT;
        public bool Lemas => Energi < CampaignTuning.Karier.EnergiLemas;
        public bool Busy => Job != KarierJob.None;
        public int SapaCount
        {
            get
            {
                int count = 0;
                for (int i = 0; i < layout.SapaPoints.Length; i++)
                    if ((SapaMask & (1 << i)) != 0) count++;
                return count;
            }
        }

        public bool Sapa(int index) => index >= 0 && (SapaMask & (1 << index)) != 0;

        public void ResetProgress()
        {
            Duit = CampaignTuning.Karier.DuitStart;
            Energi = CampaignTuning.Karier.EnergiMax;
            Restu = CampaignTuning.Karier.RestuStart;
            CatatanHitam = 0;
            SapaMask = 0;
            Registered = false;
            TripsOjol = SetKuli = PostBuzzer = PremanBeaten = 0;
            FoodBought = RideCount = 0;
            Mission = 0;
            ClearActivity();
        }

        private void ClearActivity()
        {
            Job = KarierJob.None;
            Step = KarierStep.None;
            StepProgress = 0f;
            OjolFrom = OjolTo = -1;
            KuliDelivered = 0;
            Carrying = false;
            BuzzerCooldown = 0f;
            RebahanLeft = 0f;
            Keributan = 0f;
            Shouted = MeleraiDone = false;
            CalmLeft = 0f;
            PoliceReason = KarierPoliceReason.None;
            PoliceArrived = false;
            PoliceEta = -1f;
            BeatenThisFight = false;
            Ride = KarierRide.None;
            EatLeft = 0f;
            JailLeft = 0f;
            energiCarry = 0f;
        }

        // --- Tick -------------------------------------------------------------------------

        // fighting: a standing preman is close to the hero. heroDown: the hero lies in Runtuh.
        public void Tick(KarierPoint hero, float deltaTime, bool fighting, bool heroDown)
        {
            if (deltaTime <= 0f)
                return;
            if (EatLeft > 0f)
                EatLeft = Math.Max(0f, EatLeft - deltaTime);
            if (JailLeft > 0f)
            {
                JailLeft -= deltaTime;
                if (JailLeft <= 0f)
                {
                    JailLeft = 0f;
                    Say("Masa tahanan selesai. Pintu sel dibuka: \"Jangan diulangi, ya!\"");
                    Cue(KarierCue.Notif);
                }
            }
            if (BuzzerCooldown > 0f)
                BuzzerCooldown = Math.Max(0f, BuzzerCooldown - deltaTime);

            if (RebahanLeft > 0f)
            {
                RebahanLeft -= deltaTime;
                if (RebahanLeft <= 0f)
                {
                    RebahanLeft = 0f;
                    AddEnergi(CampaignTuning.Karier.RebahanEnergi);
                    Say("Bangun dari rebahan. ENERGI +" + CampaignTuning.Karier.RebahanEnergi +
                        ". Dua jam hilang, dompet tetap tipis.");
                    Cue(KarierCue.Notif);
                }
            }

            if (!heroDown && !InJail)
                TickJob(hero, deltaTime);
            TickKeributan(deltaTime, fighting && !heroDown);
            CheckMission();
        }

        private void TickJob(KarierPoint hero, float deltaTime)
        {
            float radius = CampaignTuning.Karier.ZoneRadius;
            switch (Step)
            {
                case KarierStep.OjolJemput:
                    if (Fill(KarierPoint.Near(hero, Place(OjolFrom), radius), deltaTime, CampaignTuning.Karier.OjolPickupSeconds))
                    {
                        Step = KarierStep.OjolAntar;
                        float distance = KarierPoint.Distance(Place(OjolFrom), Place(OjolTo));
                        OjolTimeLimit = distance * CampaignTuning.Karier.OjolSecondsPerMeter + CampaignTuning.Karier.OjolGraceSeconds;
                        OjolTimeLeft = OjolTimeLimit;
                        Say("Penumpang naik. Antar ke " + PlaceName(OjolTo) + " dalam " + (int)Math.Ceiling(OjolTimeLimit) + " detik!");
                        Cue(KarierCue.Notif);
                    }
                    break;
                case KarierStep.OjolAntar:
                    OjolTimeLeft -= deltaTime;
                    if (Fill(KarierPoint.Near(hero, Place(OjolTo), radius), deltaTime, CampaignTuning.Karier.OjolPickupSeconds))
                        CompleteOjol();
                    break;
                case KarierStep.KuliAmbil:
                    if (Fill(KarierPoint.Near(hero, layout.KuliPickup, radius), deltaTime, CampaignTuning.Karier.KuliPickSeconds))
                    {
                        Carrying = true;
                        Step = KarierStep.KuliAntar;
                        Say("Sak semen " + (KuliDelivered + 1) + "/" + CampaignTuning.Karier.KuliSacks + " di pundak. Bawa ke PROYEK.");
                    }
                    break;
                case KarierStep.KuliAntar:
                    if (Fill(KarierPoint.Near(hero, layout.KuliDrop, radius), deltaTime, CampaignTuning.Karier.KuliDropSeconds))
                    {
                        Carrying = false;
                        KuliDelivered++;
                        AddEnergi(-CampaignTuning.Karier.KuliEnergiPerSack);
                        if (KuliDelivered >= CampaignTuning.Karier.KuliSacks)
                            CompleteKuli();
                        else
                        {
                            Step = KarierStep.KuliAmbil;
                            Say("Sak " + KuliDelivered + "/" + CampaignTuning.Karier.KuliSacks + " beres. Ambil lagi di TUMPUKAN SEMEN.");
                            if (Energi <= 0)
                            {
                                Say("Badan remuk, ENERGI habis. Kerja kuli berhenti tanpa upah. REBAHAN atau MAKAN dulu.");
                                Cue(KarierCue.Gagal);
                                EndJob();
                            }
                        }
                    }
                    break;
                case KarierStep.BuzzerKetik:
                    if (Fill(KarierPoint.Near(hero, layout.Warkop, radius), deltaTime, CampaignTuning.Karier.BuzzerTypeSeconds))
                        CompleteBuzzer();
                    break;
            }
        }

        // Standing in the zone fills the step; leaving resets it. True once full.
        private bool Fill(bool inside, float deltaTime, float seconds)
        {
            if (!inside)
            {
                StepProgress = 0f;
                return false;
            }
            StepProgress += deltaTime / Math.Max(0.05f, seconds);
            if (StepProgress < 1f)
                return false;
            StepProgress = 0f;
            return true;
        }

        private void TickKeributan(float deltaTime, bool fighting)
        {
            if (PoliceCalled)
                return;
            // 0.6.1: once warga shouted, someone always calls the police; they come late,
            // even when the fight is already over (owner: the police must not skip a fight).
            if (Shouted && PoliceEta < 0f)
                PoliceEta = CampaignTuning.Karier.PolisiDatangSeconds;
            if (PoliceEta > 0f)
            {
                PoliceEta -= deltaTime;
                if (PoliceEta <= 0f)
                {
                    CallPolice(KarierPoliceReason.Keributan);
                    return;
                }
            }
            if (CalmLeft > 0f)
            {
                CalmLeft = Math.Max(0f, CalmLeft - deltaTime);
                return;
            }
            if (fighting)
            {
                Keributan = Math.Min(1f, Keributan + deltaTime / CampaignTuning.Karier.KeributanFillSeconds);
                energiCarry += CampaignTuning.Karier.FightEnergiPerSecond * deltaTime;
                if (energiCarry >= 1f)
                {
                    int lost = (int)energiCarry;
                    energiCarry -= lost;
                    AddEnergi(-lost);
                }
                if (!Shouted && Keributan >= CampaignTuning.Karier.TeriakAt)
                {
                    Shouted = true;
                    Say("Warga teriak: \"WOI! ADA YANG BERANTEM!\"  Tetangga berdatangan, HP merekam, ada yang telepon polisi.");
                    Cue(KarierCue.Teriak);
                }
                if (!MeleraiDone && Keributan >= CampaignTuning.Karier.MeleraiAt)
                {
                    MeleraiDone = true;
                    CalmLeft = CampaignTuning.Karier.MeleraiSeconds;
                    Say("Pak RT melerai: \"Sudah, sudah! Malu sama tetangga!\"  Kalau masih ribut, polisi dipanggil.");
                    Cue(KarierCue.Melerai);
                }
                if (Keributan >= 1f)
                    CallPolice(KarierPoliceReason.Keributan);
            }
            else if (Keributan > 0f)
            {
                Keributan = Math.Max(0f, Keributan - deltaTime / CampaignTuning.Karier.KeributanDecaySeconds);
                if (Keributan <= 0f && PoliceEta < 0f)
                    Shouted = MeleraiDone = false;
            }
        }

        // --- Jobs -------------------------------------------------------------------------

        public bool TakeJob(KarierJob job, out string reason)
        {
            reason = null;
            if (job == KarierJob.None)
                reason = "Pilih pekerjaan dulu.";
            else if (Busy)
                reason = "Selesaikan atau batalkan kerja yang sekarang dulu.";
            else if (Rebahan)
                reason = "Masih rebahan.";
            else if (PoliceCalled)
                reason = "Urusan dengan polisi belum selesai.";
            else if (InJail)
                reason = "Masih di dalam sel.";
            else if (job == KarierJob.Ojol && Energi < CampaignTuning.Karier.OjolEnergi)
                reason = "ENERGI habis. REBAHAN atau MAKAN dulu.";
            else if (job == KarierJob.Kuli && Energi < CampaignTuning.Karier.KuliEnergiPerSack * 2)
                reason = "Terlalu lemas untuk angkat semen. REBAHAN atau MAKAN dulu.";
            else if (job == KarierJob.Buzzer && BuzzerCooldown > 0f)
                reason = "Juragan buzzer belum kirim order. Tunggu " + (int)Math.Ceiling(BuzzerCooldown) + " detik.";
            else if (job == KarierJob.Ojol && !NewOjolOrder())
                reason = "Belum ada order di sekitar.";
            if (reason != null)
                return false;

            if (Ride != KarierRide.None)
            {
                Say((Ride == KarierRide.Motor ? "Motor sewaan" : "Sepeda sewaan") + " dikembalikan dulu.");
                Ride = KarierRide.None;
            }
            Job = job;
            StepProgress = 0f;
            switch (job)
            {
                case KarierJob.Ojol:
                    Step = KarierStep.OjolJemput;
                    Say("ORDER MASUK: jemput penumpang di " + PlaceName(OjolFrom) + ", antar ke " + PlaceName(OjolTo) + ".");
                    break;
                case KarierJob.Kuli:
                    Step = KarierStep.KuliAmbil;
                    KuliDelivered = 0;
                    Say("Mandor: \"Angkut " + CampaignTuning.Karier.KuliSacks + " sak semen dari TUMPUKAN ke PROYEK. Upah dibayar kalau beres.\"");
                    break;
                case KarierJob.Buzzer:
                    Step = KarierStep.BuzzerKetik;
                    Say("Juragan buzzer: \"Duduk di WARKOP, sebar pesan ini ke semua grup WA. Jangan tanya sumbernya.\"");
                    break;
            }
            Cue(KarierCue.Notif);
            return true;
        }

        public void CancelJob()
        {
            if (!Busy)
                return;
            Say(Job == KarierJob.Kuli ? "Kerja kuli ditinggal. Mandor: \"Upah hangus, ya!\"" : "Kerja dibatalkan.");
            EndJob();
        }

        private void EndJob()
        {
            Job = KarierJob.None;
            Step = KarierStep.None;
            StepProgress = 0f;
            Carrying = false;
            KuliDelivered = 0;
            OjolFrom = OjolTo = -1;
        }

        private bool NewOjolOrder()
        {
            int count = layout.Places.Length;
            if (count < 2)
                return false;
            for (int attempt = 0; attempt < 24; attempt++)
            {
                int from = random.Next(count);
                int to = random.Next(count);
                if (from == to || KarierPoint.Distance(layout.Places[from], layout.Places[to]) < CampaignTuning.Karier.OjolMinTrip)
                    continue;
                OjolFrom = from;
                OjolTo = to;
                return true;
            }
            OjolFrom = 0;
            OjolTo = count - 1;
            return true;
        }

        public static int OjolGrossFare(float meters) =>
            Round500(CampaignTuning.Karier.OjolBaseFare + CampaignTuning.Karier.OjolFarePerMeter * Math.Max(0f, meters));

        private void CompleteOjol()
        {
            float distance = KarierPoint.Distance(Place(OjolFrom), Place(OjolTo));
            int gross = OjolGrossFare(distance);
            int cut = Round500(gross * CampaignTuning.Karier.OjolAppCut);
            int net = gross - cut;
            bool late = OjolTimeLeft < 0f;
            if (late)
                net = Round500(net * 0.5f);
            AddDuit(net);
            AddEnergi(-CampaignTuning.Karier.OjolEnergi);
            TripsOjol++;
            if (!late)
                AddRestu(CampaignTuning.Karier.OjolRestuOnTime);
            Say((late ? "TELAT! Penumpang kasih bintang 1, tarif dipotong separuh. " : "Sampai tepat waktu, bintang 5! ") +
                "Tarif " + Rupiah(gross) + " - potongan aplikasi " + Rupiah(cut) + (late ? " - denda telat" : string.Empty) +
                " = " + Rupiah(net) + ".");
            Cue(KarierCue.Koin);

            StepProgress = 0f;
            if (Energi < CampaignTuning.Karier.OjolEnergi)
            {
                Say("Lemas. Aplikasi ojol dimatikan dulu. REBAHAN atau MAKAN.");
                EndJob();
                return;
            }
            NewOjolOrder();
            Step = KarierStep.OjolJemput;
            Say("Order baru: jemput di " + PlaceName(OjolFrom) + " (buka HP untuk berhenti narik).");
        }

        private void CompleteKuli()
        {
            int net = CampaignTuning.Karier.KuliWage - CampaignTuning.Karier.KuliMandorCut;
            AddDuit(net);
            AddRestu(CampaignTuning.Karier.KuliRestu);
            SetKuli++;
            Say("UPAH KULI " + Rupiah(CampaignTuning.Karier.KuliWage) + " - uang rokok mandor " +
                Rupiah(CampaignTuning.Karier.KuliMandorCut) + " = " + Rupiah(net) + ". Kerja keras, hasil pas-pasan.");
            Cue(KarierCue.Koin);
            EndJob();
        }

        private static readonly string[] Hoaks =
        {
            "\"VIRAL! Air rebusan sandal jepit bikin kebal tilang\" terkirim ke 37 grup WA.",
            "\"Besok listrik padam seminggu, borong lilin sekarang!\" (sumber: katanya).",
            "\"Bansos cair hari ini, klik tautan ini\"  ...tautannya ternyata iklan pinjol.",
            "\"Makan mi instan pakai nasi bikin pintar\" dibagikan grup keluarga, 2.000 kali.",
            "\"Jalan kampung sudah diaspal\" lengkap dengan foto jalan negara tetangga."
        };

        private void CompleteBuzzer()
        {
            AddDuit(CampaignTuning.Karier.BuzzerPay);
            AddCatatan(CampaignTuning.Karier.BuzzerCatatan);
            AddRestu(CampaignTuning.Karier.BuzzerRestu);
            AddEnergi(-CampaignTuning.Karier.BuzzerEnergi);
            BuzzerCooldown = CampaignTuning.Karier.BuzzerCooldownSeconds;
            PostBuzzer++;
            Say(Hoaks[random.Next(Hoaks.Length)] + "  Bayaran " + Rupiah(CampaignTuning.Karier.BuzzerPay) +
                " masuk. CATATAN HITAM +" + CampaignTuning.Karier.BuzzerCatatan + ".");
            Cue(KarierCue.Koin);
            EndJob();

            // PASAL KARET: the higher the record, the likelier a report.
            if (CatatanHitam >= CampaignTuning.Karier.PasalKaretFrom)
            {
                double chance = (CatatanHitam - 40) / 100.0;
                if (random.NextDouble() < chance)
                    CallPolice(KarierPoliceReason.Hoaks);
            }
        }

        // --- Contextual actions -----------------------------------------------------------

        public KarierAction ActionAt(KarierPoint hero, out int sapaIndex)
        {
            sapaIndex = -1;
            if (Rebahan || PoliceCalled || InJail)
                return KarierAction.None;
            float radius = CampaignTuning.Karier.ZoneRadius;
            if (CanDaftar && KarierPoint.Near(hero, layout.PosRt, radius))
                return KarierAction.DaftarRT;
            for (int i = 0; i < layout.SapaPoints.Length; i++)
            {
                if (!Sapa(i) && KarierPoint.Near(hero, layout.SapaPoints[i], radius))
                {
                    sapaIndex = i;
                    return KarierAction.Sapa;
                }
            }
            if (Step != KarierStep.BuzzerKetik && KarierPoint.Near(hero, layout.Warkop, radius))
                return KarierAction.Makan;
            if (KarierPoint.Near(hero, layout.Siomay, radius))
                return KarierAction.BeliSiomay;
            if (KarierPoint.Near(hero, layout.Salome, radius))
                return KarierAction.BeliSalome;
            if (KarierPoint.Near(hero, layout.Bakso, radius))
                return KarierAction.BeliBakso;
            if (Ride == KarierRide.None && !Busy)
            {
                if (KarierPoint.Near(hero, layout.SewaSepeda, radius))
                    return KarierAction.SewaSepeda;
                if (KarierPoint.Near(hero, layout.SewaMotor, radius))
                    return KarierAction.SewaMotor;
            }
            if (Ride != KarierRide.None)
                return KarierAction.Turun;
            return KarierAction.None;
        }

        private static readonly string[] SapaLines =
        {
            "Bapak-bapak pos ronda: \"Jalan kampung bolong tiga tahun, Mas/Mbak.\"  Kamu dengarkan sampai habis kopi. RESTU +",
            "Ibu-ibu tukang sayur: \"Cabai naik lagi, gaji suami segitu-gitu aja.\"  Kamu ikut ngerumpi. RESTU +",
            "Driver ojol: \"Potongan aplikasi makin gede, bensin makin mahal.\"  Kamu kasih semangat. RESTU +"
        };

        public bool DoAction(KarierAction action, int sapaIndex)
        {
            switch (action)
            {
                case KarierAction.Makan:
                    return Eat("Nasi telur + es teh di warkop", CampaignTuning.Karier.MakanPrice, CampaignTuning.Karier.MakanEnergi);
                case KarierAction.BeliSiomay:
                    return Eat("Siomay bumbu kacang, pedasnya bikin melek", CampaignTuning.Karier.SiomayPrice, CampaignTuning.Karier.SiomayEnergi);
                case KarierAction.BeliSalome:
                    return Eat("Salome tusuk tiga, saus sambal banjir", CampaignTuning.Karier.SalomePrice, CampaignTuning.Karier.SalomeEnergi);
                case KarierAction.BeliBakso:
                    return Eat("Bakso urat semangkuk, ting-ting-ting", CampaignTuning.Karier.BaksoPrice, CampaignTuning.Karier.BaksoEnergi);
                case KarierAction.SewaSepeda:
                    return Rent(KarierRide.Sepeda, CampaignTuning.Karier.SewaSepedaPrice);
                case KarierAction.SewaMotor:
                    return Rent(KarierRide.Motor, CampaignTuning.Karier.SewaMotorPrice);
                case KarierAction.Turun:
                    if (Ride == KarierRide.None)
                        return false;
                    Say((Ride == KarierRide.Motor ? "Motor sewaan" : "Sepeda sewaan") + " dikembalikan. Jalan kaki lagi.");
                    Ride = KarierRide.None;
                    Cue(KarierCue.Notif);
                    return true;
                case KarierAction.Sapa:
                    if (sapaIndex < 0 || sapaIndex >= layout.SapaPoints.Length || Sapa(sapaIndex))
                        return false;
                    SapaMask |= 1 << sapaIndex;
                    AddRestu(CampaignTuning.Karier.SapaRestu);
                    Say(SapaLines[sapaIndex % SapaLines.Length] + CampaignTuning.Karier.SapaRestu);
                    Cue(KarierCue.Restu);
                    return true;
                case KarierAction.DaftarRT:
                    if (!CanDaftar)
                        return false;
                    AddDuit(-CampaignTuning.Karier.SyukuranRT);
                    Registered = true;
                    Say("Resmi DAFTAR CALON KETUA RT 03! Syukuran nasi kotak " + Rupiah(CampaignTuning.Karier.SyukuranRT) + " ludes.");
                    Cue(KarierCue.Daftar);
                    return true;
            }
            return false;
        }

        private bool Eat(string food, int price, int energi)
        {
            if (Eating)
                return false;
            if (Energi >= CampaignTuning.Karier.EnergiMax)
            {
                Say("Masih kenyang. ENERGI sudah penuh.");
                return false;
            }
            if (Duit < price)
            {
                Say("Duit kurang buat jajan. Penjual: \"Bon kemarin aja belum lunas!\"");
                Cue(KarierCue.Gagal);
                return false;
            }
            AddDuit(-price);
            AddEnergi(energi);
            FoodBought++;
            EatLeft = CampaignTuning.Karier.EatSeconds;
            Say(food + ". " + Rupiah(price) + ", ENERGI +" + energi + ".");
            Cue(KarierCue.Koin);
            return true;
        }

        private bool Rent(KarierRide ride, int price)
        {
            if (Ride != KarierRide.None || Busy)
                return false;
            if (Duit < price)
            {
                Say("Duit kurang buat sewa. Pemilik: \"KTP-nya ditinggal juga nggak cukup, Mas.\"");
                Cue(KarierCue.Gagal);
                return false;
            }
            AddDuit(-price);
            Ride = ride;
            RideCount++;
            Say(ride == KarierRide.Motor
                ? "Sewa motor " + Rupiah(price) + ". Helm? \"Deket kok, nggak usah.\"  Tekan TURUN untuk mengembalikan."
                : "Sewa sepeda " + Rupiah(price) + ". Kring-kring! Tekan TURUN untuk mengembalikan.");
            Cue(KarierCue.Notif);
            return true;
        }

        public bool StartRebahan(out string reason)
        {
            reason = null;
            if (Rebahan)
                reason = "Sudah rebahan.";
            else if (Busy)
                reason = "Lagi kerja. Batalkan dulu kalau mau rebahan.";
            else if (PoliceCalled || PoliceEta >= 0f)
                reason = "Polisi sedang menuju ke sini!";
            else if (InJail)
                reason = "Di sel cuma bisa duduk.";
            else if (Keributan > 0f)
                reason = "Masih ribut, mana bisa rebahan.";
            else if (Energi >= CampaignTuning.Karier.EnergiMax)
                reason = "ENERGI masih penuh. Rebahan terus nanti jadi kaum rebahan sejati.";
            if (reason != null)
                return false;
            Ride = KarierRide.None;
            RebahanLeft = CampaignTuning.Karier.RebahanSeconds;
            Say("Rebahan sambil scroll sosmed...");
            return true;
        }

        // --- Fights, police ---------------------------------------------------------------

        public void OnPremanBeaten(int count)
        {
            if (count <= 0)
                return;
            PremanBeaten += count;
            if (Shouted || Keributan > 0f || PoliceEta >= 0f)
                BeatenThisFight = true;
            AddRestu(CampaignTuning.Karier.PremanRestu * count);
            AddDuit(CampaignTuning.Karier.PremanTip);
            Say("Pemalak kabur! Tukang sayur kasih " + Rupiah(CampaignTuning.Karier.PremanTip) +
                " tanda terima kasih. RESTU +" + CampaignTuning.Karier.PremanRestu * count + ".");
            Cue(KarierCue.Restu);
        }

        public void OnHeroRuntuh()
        {
            int pay = Math.Min(Duit, CampaignTuning.Karier.PingsanBiaya);
            AddDuit(-pay);
            Energi = Math.Min(Energi, CampaignTuning.Karier.PingsanEnergi);
            EndJob();
            Ride = KarierRide.None;
            Keributan = 0f;
            Shouted = MeleraiDone = false;
            CalmLeft = 0f;
            PoliceEta = -1f;
            BeatenThisFight = false;
            if (PoliceCalled && !PoliceArrived)
                PoliceReason = KarierPoliceReason.None;
            Say("Pingsan dihajar preman. Warga gotong ke puskesmas, biaya " + Rupiah(pay) + ".");
            Cue(KarierCue.Gagal);
        }

        public void CallPolice(KarierPoliceReason reason)
        {
            if (PoliceCalled || reason == KarierPoliceReason.None)
                return;
            PoliceReason = reason;
            PoliceArrived = false;
            PoliceEta = -1f;
            Keributan = 1f;
            CalmLeft = 0f;
            Say(reason == KarierPoliceReason.Hoaks
                ? "Postinganmu viral dan dilaporkan! Polisi datang menjemput: PASAL KARET."
                : "Sirene mendekat! Polisi akhirnya datang (seperti biasa, setelah semuanya selesai).");
            Cue(KarierCue.Sirene);
        }

        public void PoliceArrive()
        {
            if (PoliceCalled)
                PoliceArrived = true;
        }

        public int DamaiPrice => PoliceReason == KarierPoliceReason.Hoaks
            ? CampaignTuning.Karier.DamaiHoaks + CatatanHitam * CampaignTuning.Karier.DamaiHoaksPerCatatan
            : CampaignTuning.Karier.DamaiFight + CatatanHitam * CampaignTuning.Karier.DamaiFightPerCatatan;

        public bool CanDamai => Duit >= DamaiPrice;

        public bool ResolvePolice(KarierPoliceChoice choice)
        {
            if (!PoliceCalled || !PoliceArrived)
                return false;
            bool hoaks = PoliceReason == KarierPoliceReason.Hoaks;
            switch (choice)
            {
                case KarierPoliceChoice.Kabur:
                    AddCatatan(CampaignTuning.Karier.KaburCatatan);
                    AddRestu(CampaignTuning.Karier.KaburRestu);
                    Say("KABUR lewat gang tikus! Lolos, tapi wajahmu sudah terekam HP warga. CATATAN HITAM +" +
                        CampaignTuning.Karier.KaburCatatan + ".");
                    break;
                case KarierPoliceChoice.Damai:
                    int price = DamaiPrice;
                    if (Duit < price)
                    {
                        Say("Dompet tipis, \"damai\" ditolak.");
                        Cue(KarierCue.Gagal);
                        return false;
                    }
                    AddDuit(-price);
                    AddCatatan(CampaignTuning.Karier.DamaiCatatan);
                    Say("DAMAI DI TEMPAT " + Rupiah(price) + ". \"Ya sudah, hati-hati di jalan.\"  Tidak ada kuitansi.");
                    break;
                case KarierPoliceChoice.Saksi:
                    if (!CanSaksi)
                        return false;
                    AddRestu(CampaignTuning.Karier.SaksiRestuGain);
                    Say("Warga jadi saksi: \"Dia yang ngusir preman, Pak!\"  Polisi manggut-manggut... lalu minta foto bareng buat laporan.");
                    break;
                case KarierPoliceChoice.Polsek:
                    AddRestu(CampaignTuning.Karier.PolsekRestu);
                    AddEnergi(CampaignTuning.Karier.PolsekEnergi);
                    AddCatatan(hoaks ? CampaignTuning.Karier.ArrestPolsekCatatan : CampaignTuning.Karier.PolsekCatatan);
                    Say("Tangan diborgol. \"Ikut kami ke POLSEK!\"  Ibu-ibu langsung kirim videonya ke grup.");
                    EndJob();
                    Ride = KarierRide.None;
                    break;
            }
            PoliceReason = KarierPoliceReason.None;
            PoliceArrived = false;
            PoliceEta = -1f;
            BeatenThisFight = false;
            Keributan = 0f;
            Shouted = MeleraiDone = false;
            CalmLeft = 0f;
            Cue(KarierCue.Notif);
            return true;
        }

        // The hero sits in the POLSEK cell (after the arrest ride).
        public void EnterJail()
        {
            JailLeft = CampaignTuning.Karier.JailSeconds;
            Say("Masuk sel POLSEK KONOHA. Tunggu " + (int)CampaignTuning.Karier.JailSeconds +
                " detik, atau TEBUS " + Rupiah(TebusPrice) + " (tanpa kuitansi).");
        }

        public bool Tebus()
        {
            if (!InJail)
                return false;
            int price = TebusPrice;
            if (Duit < price)
            {
                Say("Duit tidak cukup untuk \"uang jaminan\". Silakan menikmati sel.");
                Cue(KarierCue.Gagal);
                return false;
            }
            AddDuit(-price);
            JailLeft = 0f;
            Say("Uang jaminan " + Rupiah(price) + " diterima. Pintu sel tiba-tiba terbuka.");
            Cue(KarierCue.Koin);
            return true;
        }

        // --- Missions (0.6.1): a long chain that teaches the life and ends at Ketua RT -------

        public const int MisiTawaran = 5;

        public static readonly string[] MissionTitles =
        {
            "KERJA PERTAMA", "KENALAN TETANGGA", "JAJAN DULU", "COBA KENDARAAN", "PAHLAWAN GANG",
            "TAWARAN GELAP", "TABUNGAN", "RESTU WARGA", "DAFTAR CALON RT"
        };

        private static readonly string[] MissionIntro =
        {
            "Ibu kos (WA): \"Kontrakan bulan ini belum dibayar ya. Cari kerja dulu: OJOL atau KULI.\"",
            "Pak RT (WA): \"Kalau mau dikenal, sapa warga: bapak-bapak pos ronda, ibu-ibu, driver ojol.\"",
            "Perut keroncongan. Jajan siomay, salome, bakso, atau makan di warkop.",
            "Di dekat gerbang ada SEWA SEPEDA, di pangkalan ojol ada SEWA MOTOR. Coba salah satu.",
            "Warga (WA): \"Preman di mulut gang malak lagi. Ada yang berani?\"",
            "Nomor tak dikenal (WA): \"Mau duit cepat? Sebar pesan ini ke grup. Rp 250rb langsung cair.\"",
            "Syukuran RT butuh modal. Kumpulkan dulu tabungan " + Rupiah(CampaignTuning.Karier.MisiTabungan) + ".",
            "Pak Haji: \"Calon RT harus dipercaya warga.\"  Kumpulkan RESTU " + CampaignTuning.Karier.RestuSyaratRT + ".",
            "Syarat hampir lengkap: " + Rupiah(CampaignTuning.Karier.SyukuranRT) + " untuk syukuran, lalu DAFTAR di POS RONDA."
        };

        public bool AllMissionsDone => Mission >= MissionTitles.Length;

        public string MissionTitle => AllMissionsDone ? "MENUNGGU PEMILIHAN" : MissionTitles[Mission];

        public string MissionProgress
        {
            get
            {
                switch (Mission)
                {
                    case 0: return "Selesaikan 1 antar OJOL atau 1 set KULI";
                    case 1: return "Sapa warga " + SapaCount + "/" + layout.SapaPoints.Length;
                    case 2: return "Beli jajanan atau makan";
                    case 3: return "Sewa sepeda atau motor";
                    case 4: return "Usir preman di mulut gang";
                    case 5: return "Jawab WA nomor tak dikenal";
                    case 6: return "Tabungan " + Rupiah(Duit) + " / " + Rupiah(CampaignTuning.Karier.MisiTabungan);
                    case 7: return "RESTU " + Restu + " / " + CampaignTuning.Karier.RestuSyaratRT;
                    case 8: return "DAFTAR di POS RONDA (" + Rupiah(CampaignTuning.Karier.SyukuranRT) + ")";
                    default: return "Pemilihan Ketua RT hadir di versi berikutnya";
                }
            }
        }

        public string MissionIntroText => AllMissionsDone ? string.Empty : MissionIntro[Mission];

        private bool MissionDone(int index)
        {
            switch (index)
            {
                case 0: return TripsOjol > 0 || SetKuli > 0;
                case 1: return SapaCount >= layout.SapaPoints.Length;
                case 2: return FoodBought > 0;
                case 3: return RideCount > 0;
                case 4: return PremanBeaten > 0;
                case 5: return false; // Answered through AnswerOffer.
                case 6: return Duit >= CampaignTuning.Karier.MisiTabungan;
                case 7: return Restu >= CampaignTuning.Karier.RestuSyaratRT;
                case 8: return Registered;
                default: return false;
            }
        }

        private void CheckMission()
        {
            // Several can finish at once (e.g. a loaded save); one per tick keeps messages readable.
            if (!AllMissionsDone && MissionDone(Mission))
                CompleteMission();
        }

        private void CompleteMission()
        {
            int done = Mission;
            switch (done)
            {
                case 0: AddDuit(CampaignTuning.Karier.MisiKerjaReward); break;
                case 1: AddRestu(CampaignTuning.Karier.SapaRestu); break;
                case 2: AddEnergi(10); break;
                case 4: AddRestu(CampaignTuning.Karier.SapaRestu); break;
                case 6: AddRestu(3); break;
            }
            Mission++;
            Say("MISI SELESAI: " + MissionTitles[done] + (done == 0 ? " (+" + Rupiah(CampaignTuning.Karier.MisiKerjaReward) + ")" : string.Empty) + ".");
            if (!AllMissionsDone)
                Say(MissionIntro[Mission]);
            Cue(KarierCue.Misi);
        }

        // TAWARAN GELAP: accept (fast money, record) or refuse (restu).
        public bool AnswerOffer(bool accept)
        {
            if (!OfferPending)
                return false;
            if (accept)
            {
                AddDuit(CampaignTuning.Karier.TawaranPay);
                AddCatatan(CampaignTuning.Karier.TawaranCatatan);
                AddRestu(-2);
                PostBuzzer++;
                Say("Pesan diteruskan ke 12 grup. " + Rupiah(CampaignTuning.Karier.TawaranPay) + " masuk. CATATAN HITAM +" +
                    CampaignTuning.Karier.TawaranCatatan + ". Nomor itu lalu hilang.");
            }
            else
            {
                AddRestu(CampaignTuning.Karier.TolakRestu);
                Say("Kamu blokir nomornya dan lapor ke grup RT. Pak RT: \"Mantap, hati-hati penipuan!\" RESTU +" +
                    CampaignTuning.Karier.TolakRestu + ".");
            }
            CompleteMission();
            return true;
        }

        // --- Helpers ------------------------------------------------------------------------

        public KarierPoint Place(int index) =>
            index >= 0 && index < layout.Places.Length ? layout.Places[index] : new KarierPoint(0f, 0f);

        public string PlaceName(int index) =>
            index >= 0 && index < layout.PlaceNames.Length ? layout.PlaceNames[index] : "TUJUAN";

        // Where the current step wants the hero; false when nothing is pending.
        public bool Target(out KarierPoint point, out string label)
        {
            switch (Step)
            {
                case KarierStep.OjolJemput: point = Place(OjolFrom); label = "JEMPUT: " + PlaceName(OjolFrom); return true;
                case KarierStep.OjolAntar: point = Place(OjolTo); label = "ANTAR: " + PlaceName(OjolTo); return true;
                case KarierStep.KuliAmbil: point = layout.KuliPickup; label = "TUMPUKAN SEMEN"; return true;
                case KarierStep.KuliAntar: point = layout.KuliDrop; label = "PROYEK"; return true;
                case KarierStep.BuzzerKetik: point = layout.Warkop; label = "WARKOP"; return true;
            }
            if (CanDaftar)
            {
                point = layout.PosRt;
                label = "DAFTAR RT: POS RONDA";
                return true;
            }
            if (!InJail && !PoliceCalled)
            {
                // 0.6.1: the current mission points the way when no job runs.
                switch (Mission)
                {
                    case 1:
                        for (int i = 0; i < layout.SapaPoints.Length; i++)
                            if (!Sapa(i))
                            {
                                point = layout.SapaPoints[i];
                                label = "SAPA: " + (i < layout.SapaNames.Length ? layout.SapaNames[i] : "WARGA");
                                return true;
                            }
                        break;
                    case 2:
                        point = layout.Siomay;
                        label = "JAJAN: SIOMAY";
                        return true;
                    case 3:
                        if (Ride == KarierRide.None)
                        {
                            point = layout.SewaSepeda;
                            label = "SEWA SEPEDA";
                            return true;
                        }
                        break;
                }
            }
            point = new KarierPoint(0f, 0f);
            label = string.Empty;
            return false;
        }

        public void AddDuit(int amount) => Duit = Math.Max(0, Duit + amount);
        public void AddEnergi(int amount) => Energi = Clamp(Energi + amount, 0, CampaignTuning.Karier.EnergiMax);
        public void AddRestu(int amount) => Restu = Clamp(Restu + amount, 0, CampaignTuning.Karier.RestuMax);
        public void AddCatatan(int amount) => CatatanHitam = Clamp(CatatanHitam + amount, 0, CampaignTuning.Karier.CatatanMax);

        private static int Clamp(int value, int min, int max) => value < min ? min : value > max ? max : value;

        public static int Round500(float value) => (int)Math.Round(value / 500.0, MidpointRounding.AwayFromZero) * 500;

        // "Rp 1.250.000" (Indonesian thousands separator).
        public static string Rupiah(int value)
        {
            string digits = Math.Abs(value).ToString(CultureInfo.InvariantCulture);
            var builder = new StringBuilder(digits.Length + 6);
            for (int i = 0; i < digits.Length; i++)
            {
                if (i > 0 && (digits.Length - i) % 3 == 0)
                    builder.Append('.');
                builder.Append(digits[i]);
            }
            return (value < 0 ? "-Rp " : "Rp ") + builder;
        }

        private void Say(string message) => Notified?.Invoke(message);
        private void Cue(KarierCue cue) => Cued?.Invoke(cue);

        // --- Save (PlayerPrefs on the tablet) ----------------------------------------------

        public string Serialize()
        {
            return string.Join(";", new[]
            {
                "K2", Duit.ToString(CultureInfo.InvariantCulture), Energi.ToString(CultureInfo.InvariantCulture),
                Restu.ToString(CultureInfo.InvariantCulture), CatatanHitam.ToString(CultureInfo.InvariantCulture),
                SapaMask.ToString(CultureInfo.InvariantCulture), Registered ? "1" : "0",
                TripsOjol.ToString(CultureInfo.InvariantCulture), SetKuli.ToString(CultureInfo.InvariantCulture),
                PostBuzzer.ToString(CultureInfo.InvariantCulture), PremanBeaten.ToString(CultureInfo.InvariantCulture),
                Mission.ToString(CultureInfo.InvariantCulture), FoodBought.ToString(CultureInfo.InvariantCulture),
                RideCount.ToString(CultureInfo.InvariantCulture)
            });
        }

        public bool TryLoad(string text)
        {
            if (string.IsNullOrEmpty(text))
                return false;
            string[] parts = text.Split(';');
            // K1 = 0.6.0 save (no missions), K2 = 0.6.1.
            bool v1 = parts.Length == 11 && parts[0] == "K1";
            bool v2 = parts.Length == 14 && parts[0] == "K2";
            if (!v1 && !v2)
                return false;
            var values = new int[parts.Length - 1];
            for (int i = 0; i < values.Length; i++)
                if (!KarierAvatar.Int(parts[i + 1], out values[i]))
                    return false;
            ResetProgress();
            Duit = Math.Max(0, values[0]);
            Energi = Clamp(values[1], 0, CampaignTuning.Karier.EnergiMax);
            Restu = Clamp(values[2], 0, CampaignTuning.Karier.RestuMax);
            CatatanHitam = Clamp(values[3], 0, CampaignTuning.Karier.CatatanMax);
            SapaMask = Math.Max(0, values[4]);
            Registered = values[5] == 1;
            TripsOjol = Math.Max(0, values[6]);
            SetKuli = Math.Max(0, values[7]);
            PostBuzzer = Math.Max(0, values[8]);
            PremanBeaten = Math.Max(0, values[9]);
            if (v2)
            {
                Mission = Clamp(values[10], 0, MissionTitles.Length);
                FoodBought = Math.Max(0, values[11]);
                RideCount = Math.Max(0, values[12]);
            }
            return true;
        }
    }
}
