using System;
using System.Globalization;
using System.Text;

namespace Konoha.Campaign
{
    // 0.6.0 KARIER Level 1 "Warga Biasa" (Docs/VISI_KONOHA_HIDUP_v3.md §3): the life of an
    // ordinary Konoha citizen who wants to become Ketua RT. Plain C# (EditMode tested): the
    // scene side (KarierController) feeds the hero position and the fight state and shows
    // the results. Money must be earned first; dirty money is fast but leaves a record.

    // Ground position (x, z) without UnityEngine.
    public struct KarierPoint
    {
        public readonly float X, Z;

        public KarierPoint(float x, float z)
        {
            X = x;
            Z = z;
        }

        public static float Distance(KarierPoint a, KarierPoint b)
        {
            float dx = a.X - b.X, dz = a.Z - b.Z;
            return (float)Math.Sqrt(dx * dx + dz * dz);
        }

        public static bool Near(KarierPoint a, KarierPoint b, float radius) => Distance(a, b) <= radius;
    }

    // Where things happen in the city (generated by CampaignPreviewProject).
    public sealed class KarierLayout
    {
        public string[] PlaceNames = new string[0];
        public KarierPoint[] Places = new KarierPoint[0];
        public KarierPoint KuliPickup, KuliDrop, Warkop, PosRt;
        // 0.6.1: jajan stalls and rentals.
        public KarierPoint Siomay, Salome, Bakso, SewaSepeda, SewaMotor;
        // 0.6.2: where the gang preman stand and the plaza (missions).
        public KarierPoint PremanSpot, Plaza;
        // 0.6.3: PARKIR liar and the RONDA MALAM round (ends at the pos ronda).
        public KarierPoint Parkir;
        public KarierPoint[] RondaPoints = new KarierPoint[0];
        public string[] RondaNames = new string[0];
        public string[] SapaNames = new string[0];
        public KarierPoint[] SapaPoints = new KarierPoint[0];
    }

    public enum KarierJob { None, Ojol, Kuli, Buzzer, Parkir, Ronda }

    public enum KarierStep { None, OjolJemput, OjolAntar, KuliAmbil, KuliAntar, BuzzerKetik, ParkirJaga, RondaKeliling, RondaPulang }

    public enum KarierPoliceReason { None, Keributan, Hoaks, TabrakLari }

    // 0.6.3 TUGAS HARIAN kinds (counted from the life counters).
    public enum KarierTugas { Ojol, Kuli, Parkir, Ronda, Jajan }

    public enum KarierPoliceChoice { Kabur, Damai, Polsek, Saksi }

    public enum KarierCue { Notif, Koin, Gagal, Teriak, Melerai, Sirene, Restu, Daftar, Misi, Tabrak, Peluit }

    public enum KarierAction { None, Makan, Sapa, DaftarRT, BeliSiomay, BeliSalome, BeliBakso, SewaSepeda, SewaMotor, Turun }

    public enum KarierRide { None, Sepeda, Motor }

    // The player's own citizen (character creator). Indices pick from the name lists.
    public struct KarierAvatar
    {
        public static readonly string[] SkinNames = { "LANGSAT", "SAWO MATANG", "SAWO GELAP", "KUNING LANGSAT" };
        public static readonly string[] HairNames = { "RAMBUT PENDEK", "RAMBUT PANJANG", "PECI", "JILBAB", "TOPI" };
        public static readonly string[] BodyNames = { "KURUS", "SEDANG", "BERISI" };
        public static readonly string[] ShirtNames = { "PUTIH", "HITAM", "MERAH", "BIRU", "HIJAU", "KUNING", "ABU-ABU" };
        public const int MaxNameLength = 14;

        public string Name;
        public bool Female;
        public int Skin, Hair, Body, Shirt;

        public static KarierAvatar Default => new KarierAvatar { Name = "WARGA", Female = false, Skin = 1, Hair = 0, Body = 1, Shirt = 0 };

        public KarierAvatar Clamped()
        {
            KarierAvatar result = this;
            result.Name = CleanName(Name);
            result.Skin = Wrap(Skin, SkinNames.Length);
            result.Hair = Wrap(Hair, HairNames.Length);
            result.Body = Wrap(Body, BodyNames.Length);
            result.Shirt = Wrap(Shirt, ShirtNames.Length);
            return result;
        }

        public static int Wrap(int value, int count) => count <= 0 ? 0 : ((value % count) + count) % count;

        // Upper case letters, digits and spaces, at most 14 characters; never empty.
        public static string CleanName(string raw)
        {
            if (string.IsNullOrEmpty(raw))
                return "WARGA";
            var builder = new StringBuilder(MaxNameLength);
            foreach (char c in raw.ToUpperInvariant())
            {
                if (builder.Length >= MaxNameLength)
                    break;
                if ((c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || (c == ' ' && builder.Length > 0))
                    builder.Append(c);
            }
            string name = builder.ToString().Trim();
            return name.Length == 0 ? "WARGA" : name;
        }

        public string Serialize()
        {
            KarierAvatar a = Clamped();
            return "A1;" + a.Name + ";" + (a.Female ? 1 : 0) + ";" + a.Skin + ";" + a.Hair + ";" + a.Body + ";" + a.Shirt;
        }

        public static bool TryParse(string text, out KarierAvatar avatar)
        {
            avatar = Default;
            if (string.IsNullOrEmpty(text))
                return false;
            string[] parts = text.Split(';');
            if (parts.Length != 7 || parts[0] != "A1")
                return false;
            if (!Int(parts[2], out int female) || !Int(parts[3], out int skin) || !Int(parts[4], out int hair) ||
                !Int(parts[5], out int body) || !Int(parts[6], out int shirt))
                return false;
            avatar = new KarierAvatar { Name = parts[1], Female = female == 1, Skin = skin, Hair = hair, Body = body, Shirt = shirt }.Clamped();
            return true;
        }

        internal static bool Int(string text, out int value) =>
            int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
    }

    public sealed class KarierLife
    {
        public event Action<string> Notified;
        public event Action<KarierCue> Cued;

        private readonly KarierLayout layout;
        private readonly Random random;
        private float energiCarry;

        public KarierLife(KarierLayout layout, int seed = 603)
        {
            this.layout = layout ?? new KarierLayout();
            random = new Random(seed);
            ResetProgress();
        }

        // --- Resources (saved) ----------------------------------------------------------
        public int Duit { get; private set; }
        public int Energi { get; private set; }
        public int Restu { get; private set; }
        public int CatatanHitam { get; private set; }
        public int SapaMask { get; private set; }
        public bool Registered { get; private set; }
        public int TripsOjol { get; private set; }
        public int SetKuli { get; private set; }
        public int PostBuzzer { get; private set; }
        public int PremanBeaten { get; private set; }
        public int FoodBought { get; private set; }
        public int RideCount { get; private set; }
        // 0.6.1 missions (index into Missions; Missions.Length = all done).
        public int Mission { get; private set; }
        public bool OfferPending => Mission == MisiTawaran;
        // 0.6.3: day and clock (minutes after midnight), the new jobs, daily tasks.
        public int Day { get; private set; } = 1;
        public float Clock { get; private set; } = CampaignTuning.Karier.StartClock;
        public int ParkirCount { get; private set; }
        public int RondaCount { get; private set; }
        public int TabrakCount { get; private set; }
        public int TugasDay { get; private set; }
        public int TugasMask { get; private set; }
        private readonly int[] tugasBase = new int[3];
        // The congratulations after the last mission (shown once, then saved as seen).
        public bool CelebrationPending { get; private set; }
        private bool celebrationSeen;

        // --- Current activity (not saved) -------------------------------------------------
        public KarierJob Job { get; private set; }
        public KarierStep Step { get; private set; }
        public float StepProgress { get; private set; }
        public int OjolFrom { get; private set; } = -1;
        public int OjolTo { get; private set; } = -1;
        public float OjolTimeLeft { get; private set; }
        public float OjolTimeLimit { get; private set; }
        public int KuliDelivered { get; private set; }
        public bool Carrying { get; private set; }
        public float BuzzerCooldown { get; private set; }
        public float RebahanLeft { get; private set; }
        public bool Rebahan => RebahanLeft > 0f;
        public KarierRide Ride { get; private set; }
        public float EatLeft { get; private set; }
        public bool Eating => EatLeft > 0f;
        public float JailLeft { get; private set; }
        public bool InJail => JailLeft > 0f;
        // 0.6.3 activity: TIDUR, PARKIR, RONDA, TABRAK and the chase.
        public float TidurLeft { get; private set; }
        public bool Tidur => TidurLeft > 0f;
        public int ParkirMotorsDone { get; private set; }
        public int RondaIndex { get; private set; }
        public bool TabrakPending { get; private set; }
        public KarierPoint TabrakAt { get; private set; }
        public bool Chasing { get; private set; }
        public float ChaseLeft { get; private set; }
        private float tabrakCooldown;

        // --- Keributan and police -------------------------------------------------------
        public float Keributan { get; private set; }
        public bool Shouted { get; private set; }
        public bool MeleraiDone { get; private set; }
        public float CalmLeft { get; private set; }
        public bool MeleraiActive => CalmLeft > 0f;
        public KarierPoliceReason PoliceReason { get; private set; }
        public bool PoliceArrived { get; private set; }
        public bool PoliceCalled => PoliceReason != KarierPoliceReason.None;
        // 0.6.1: seconds until the police arrive after warga shouted (-1 = not on the way).
        public float PoliceEta { get; private set; } = -1f;
        public bool BeatenThisFight { get; private set; }
        public bool CanKabur => PoliceReason != KarierPoliceReason.TabrakLari;
        public bool CanSaksi => PoliceReason == KarierPoliceReason.Keributan && BeatenThisFight &&
            Restu >= CampaignTuning.Karier.SaksiRestu;
        public int TebusPrice => CampaignTuning.Karier.TebusBase + CatatanHitam * CampaignTuning.Karier.TebusPerCatatan;

        public KarierLayout Layout => layout;
        public bool CanDaftar => !Registered && Duit >= CampaignTuning.Karier.SyukuranRT && Restu >= CampaignTuning.Karier.RestuSyaratRT;
        public bool Lemas => Energi < CampaignTuning.Karier.EnergiLemas;
        public bool Busy => Job != KarierJob.None;
        public int SapaCount
        {
            get
            {
                int count = 0;
                for (int i = 0; i < layout.SapaPoints.Length; i++)
                    if ((SapaMask & (1 << i)) != 0) count++;
                return count;
            }
        }

        public bool Sapa(int index) => index >= 0 && (SapaMask & (1 << index)) != 0;

        public void ResetProgress()
        {
            Duit = CampaignTuning.Karier.DuitStart;
            Energi = CampaignTuning.Karier.EnergiMax;
            Restu = CampaignTuning.Karier.RestuStart;
            CatatanHitam = 0;
            SapaMask = 0;
            Registered = false;
            TripsOjol = SetKuli = PostBuzzer = PremanBeaten = 0;
            FoodBought = RideCount = 0;
            RebahanCount = 0;
            RodeToPlaza = false;
            Mission = 0;
            Day = 1;
            Clock = CampaignTuning.Karier.StartClock;
            ParkirCount = RondaCount = TabrakCount = 0;
            TugasDay = 0;
            TugasMask = 0;
            tugasBase[0] = tugasBase[1] = tugasBase[2] = 0;
            CelebrationPending = false;
            celebrationSeen = false;
            ClearActivity();
        }

        private void ClearActivity()
        {
            Job = KarierJob.None;
            Step = KarierStep.None;
            StepProgress = 0f;
            OjolFrom = OjolTo = -1;
            KuliDelivered = 0;
            Carrying = false;
            BuzzerCooldown = 0f;
            RebahanLeft = 0f;
            Keributan = 0f;
            Shouted = MeleraiDone = false;
            CalmLeft = 0f;
            PoliceReason = KarierPoliceReason.None;
            PoliceArrived = false;
            PoliceEta = -1f;
            BeatenThisFight = false;
            Ride = KarierRide.None;
            EatLeft = 0f;
            JailLeft = 0f;
            energiCarry = 0f;
            TidurLeft = 0f;
            ParkirMotorsDone = 0;
            RondaIndex = 0;
            TabrakPending = false;
            Chasing = false;
            ChaseLeft = 0f;
            tabrakCooldown = 0f;
        }

        // --- Tick -------------------------------------------------------------------------

        // fighting: a standing preman is close to the hero. heroDown: the hero lies in Runtuh.
        private KarierPoint? lastHero;

        public void Tick(KarierPoint hero, float deltaTime, bool fighting, bool heroDown)
        {
            lastHero = hero;
            if (deltaTime <= 0f)
                return;
            AdvanceClock(deltaTime * 1440f / CampaignTuning.Karier.DaySeconds);
            if (tabrakCooldown > 0f)
                tabrakCooldown = Math.Max(0f, tabrakCooldown - deltaTime);
            if (TidurLeft > 0f)
            {
                TidurLeft -= deltaTime;
                if (TidurLeft <= 0f)
                    WakeUp();
            }
            TickTabrak(hero, deltaTime);
            if (EatLeft > 0f)
                EatLeft = Math.Max(0f, EatLeft - deltaTime);
            if (JailLeft > 0f)
            {
                JailLeft -= deltaTime;
                if (JailLeft <= 0f)
                {
                    JailLeft = 0f;
                    Say("Masa tahanan selesai. Pintu sel dibuka: \"Jangan diulangi, ya!\"");
                    Cue(KarierCue.Notif);
                }
            }
            if (BuzzerCooldown > 0f)
                BuzzerCooldown = Math.Max(0f, BuzzerCooldown - deltaTime);

            if (RebahanLeft > 0f)
            {
                RebahanLeft -= deltaTime;
                if (RebahanLeft <= 0f)
                {
                    RebahanLeft = 0f;
                    AddEnergi(CampaignTuning.Karier.RebahanEnergi);
                    AdvanceClock(CampaignTuning.Karier.RebahanMinutes);
                    Say("Bangun dari rebahan. ENERGI +" + CampaignTuning.Karier.RebahanEnergi +
                        ". Dua jam hilang, dompet tetap tipis.");
                    Cue(KarierCue.Notif);
                }
            }

            if (!heroDown && !InJail)
                TickJob(hero, deltaTime);
            TickKeributan(deltaTime, fighting && !heroDown);
            CheckMission();
            CheckTugas();
        }

        // --- 0.6.3 Day and night ------------------------------------------------------------

        public bool Night => Clock >= CampaignTuning.Karier.NightFrom || Clock < CampaignTuning.Karier.NightUntil;

        // 0 at midnight, 0.5 at noon (for the sun).
        public float DayFraction => Clock / 1440f;

        public string ClockText
        {
            get
            {
                int minutes = (int)Clock;
                return (minutes / 60).ToString("00", CultureInfo.InvariantCulture) + "." + (minutes % 60).ToString("00", CultureInfo.InvariantCulture);
            }
        }

        public string DayPart
        {
            get
            {
                int hour = (int)Clock / 60;
                if (hour < 4) return "DINI HARI";
                if (hour < 10) return "PAGI";
                if (hour < 15) return "SIANG";
                if (hour < 18) return "SORE";
                return "MALAM";
            }
        }

        // Is the clock inside [from, until) (wrapping past midnight)?
        public static bool Between(float clock, int from, int until) =>
            from <= until ? clock >= from && clock < until : clock >= from || clock < until;

        public bool CanTidurNow => Between(Clock, CampaignTuning.Karier.TidurFrom, CampaignTuning.Karier.TidurUntil);

        private void AdvanceClock(float minutes)
        {
            if (minutes <= 0f)
                return;
            Clock += minutes;
            while (Clock >= 1440f)
            {
                Clock -= 1440f;
                Day++;
                Say("HARI KE-" + Day + " dimulai (" + ClockText + "). Tugas harian baru, cicilan juga baru.");
            }
        }

        public bool StartTidur(out string reason)
        {
            reason = null;
            if (Tidur)
                reason = "Sudah tidur.";
            else if (!CanTidurNow)
                reason = "Belum malam. TIDUR bisa jam 19.00 sampai 04.00 (siang cukup REBAHAN).";
            else if (Busy)
                reason = "Lagi kerja. Batalkan dulu kalau mau tidur.";
            else if (PoliceCalled || PoliceEta >= 0f || TabrakPending)
                reason = "Urusan belum selesai, mana bisa tidur.";
            else if (InJail)
                reason = "Tidur di sel? Tunggu bebas dulu.";
            else if (Keributan > 0f)
                reason = "Masih ribut, mana bisa tidur.";
            if (reason != null)
                return false;
            Ride = KarierRide.None;
            RebahanLeft = 0f;
            TidurLeft = CampaignTuning.Karier.TidurSeconds;
            Say("Pulang ke kontrakan, lampu dimatikan... Zzz.");
            return true;
        }

        private void WakeUp()
        {
            TidurLeft = 0f;
            // Asleep in the evening: the night passes midnight, a new day starts.
            float minutes = Clock < CampaignTuning.Karier.MorningClock
                ? CampaignTuning.Karier.MorningClock - Clock
                : 1440f - Clock + CampaignTuning.Karier.MorningClock;
            AdvanceClock(minutes);
            Energi = CampaignTuning.Karier.EnergiMax;
            Say("Bangun jam 06.00, ENERGI penuh. Ayam tetangga sudah berkokok dari tadi.");
            Cue(KarierCue.Notif);
        }

        private static bool OpenNow(float clock, KarierJob job, out string reason)
        {
            reason = null;
            if (job == KarierJob.Kuli && !Between(clock, CampaignTuning.Karier.KuliFrom, CampaignTuning.Karier.KuliUntil))
                reason = "Proyek tutup. Mandor cuma cari kuli jam 07.00-17.00.";
            else if (job == KarierJob.Parkir && !Between(clock, CampaignTuning.Karier.ParkirFrom, CampaignTuning.Karier.ParkirUntil))
                reason = "Kantor kelurahan tutup, nggak ada motor parkir. PARKIR jam 08.00-21.00.";
            else if (job == KarierJob.Ronda && !Between(clock, CampaignTuning.Karier.RondaFrom, CampaignTuning.Karier.RondaUntil))
                reason = "RONDA MALAM mulai jam 21.00 (sampai 03.00).";
            return reason == null;
        }

        public bool JobOpen(KarierJob job) => OpenNow(Clock, job, out _);

        // --- 0.6.3 TABRAK: riding into a warga ------------------------------------------------

        public bool Riding => Ride != KarierRide.None || Job == KarierJob.Ojol;

        public bool CanTabrak => Riding && !TabrakPending && !PoliceCalled && !InJail && tabrakCooldown <= 0f;

        public void OnTabrak(KarierPoint at)
        {
            if (!CanTabrak)
                return;
            TabrakPending = true;
            TabrakAt = at;
            TabrakCount++;
            Say("BRAK! Kamu menabrak warga! Warga teriak: \"TABRAK! TABRAK!\"  Berhenti dan TANGGUNG JAWAB, atau KABUR?");
            Cue(KarierCue.Tabrak);
        }

        public int GantiRugiPrice => CampaignTuning.Karier.TabrakGantiRugi;

        public bool TanggungJawab()
        {
            if (!TabrakPending)
                return false;
            int price = GantiRugiPrice;
            bool short_ = Duit < price;
            AddDuit(-price);
            AddRestu(CampaignTuning.Karier.TabrakTanggungRestu);
            TabrakPending = false;
            tabrakCooldown = CampaignTuning.Karier.TabrakCooldown;
            Say(short_
                ? "Kamu antar korban ke puskesmas. Dompet terkuras, sisanya dicicil. Warga: \"Untung dia mau tanggung jawab.\""
                : "Kamu antar korban ke puskesmas dan bayar " + Rupiah(price) + ". Warga: \"Nah, gitu dong, gentleman.\"");
            Cue(KarierCue.Koin);
            return true;
        }

        public bool KaburTabrak()
        {
            if (!TabrakPending)
                return false;
            TabrakPending = false;
            AddCatatan(CampaignTuning.Karier.TabrakKaburCatatan);
            AddRestu(CampaignTuning.Karier.TabrakKaburRestu);
            PoliceReason = KarierPoliceReason.TabrakLari;
            PoliceArrived = false;
            PoliceEta = -1f;
            Chasing = true;
            ChaseLeft = CampaignTuning.Karier.ChaseSeconds;
            Say("TABRAK LARI! Warga merekam platmu, polisi patroli MENGEJAR. Lolos " + (int)CampaignTuning.Karier.ChaseSeconds +
                " detik atau tertangkap. CATATAN HITAM +" + CampaignTuning.Karier.TabrakKaburCatatan + ".");
            Cue(KarierCue.Sirene);
            return true;
        }

        private void TickTabrak(KarierPoint hero, float deltaTime)
        {
            // Riding away from the crash is KABUR, whatever the panel says.
            if (TabrakPending && KarierPoint.Distance(hero, TabrakAt) > CampaignTuning.Karier.TabrakKaburDistance)
                KaburTabrak();
            if (!Chasing || PoliceArrived)
                return;
            ChaseLeft -= deltaTime;
            if (ChaseLeft > 0f)
                return;
            Chasing = false;
            ChaseLeft = 0f;
            PoliceReason = KarierPoliceReason.None;
            tabrakCooldown = CampaignTuning.Karier.TabrakCooldown;
            Say("LOLOS dari kejaran polisi... tapi videonya sudah viral di grup RT. CATATAN HITAM tidak hilang.");
            Cue(KarierCue.Notif);
        }

        // The patrol motor reached the fleeing hero.
        public void CaughtInChase()
        {
            if (!Chasing)
                return;
            Chasing = false;
            PoliceArrived = true;
            Say("TERTANGKAP! Polisi memotong jalanmu: \"Turun! Tunjukkan SIM dan STNK!\"");
            Cue(KarierCue.Sirene);
        }

        private void TickJob(KarierPoint hero, float deltaTime)
        {
            float radius = CampaignTuning.Karier.ZoneRadius;
            switch (Step)
            {
                case KarierStep.OjolJemput:
                    if (Fill(KarierPoint.Near(hero, Place(OjolFrom), radius), deltaTime, CampaignTuning.Karier.OjolPickupSeconds))
                    {
                        Step = KarierStep.OjolAntar;
                        float distance = KarierPoint.Distance(Place(OjolFrom), Place(OjolTo));
                        OjolTimeLimit = distance * CampaignTuning.Karier.OjolSecondsPerMeter + CampaignTuning.Karier.OjolGraceSeconds;
                        OjolTimeLeft = OjolTimeLimit;
                        Say("Penumpang naik. Antar ke " + PlaceName(OjolTo) + " dalam " + (int)Math.Ceiling(OjolTimeLimit) + " detik!");
                        Cue(KarierCue.Notif);
                    }
                    break;
                case KarierStep.OjolAntar:
                    OjolTimeLeft -= deltaTime;
                    if (Fill(KarierPoint.Near(hero, Place(OjolTo), radius), deltaTime, CampaignTuning.Karier.OjolPickupSeconds))
                        CompleteOjol();
                    break;
                case KarierStep.KuliAmbil:
                    if (Fill(KarierPoint.Near(hero, layout.KuliPickup, radius), deltaTime, CampaignTuning.Karier.KuliPickSeconds))
                    {
                        Carrying = true;
                        Step = KarierStep.KuliAntar;
                        Say("Sak semen " + (KuliDelivered + 1) + "/" + CampaignTuning.Karier.KuliSacks + " di pundak. Bawa ke PROYEK.");
                    }
                    break;
                case KarierStep.KuliAntar:
                    if (Fill(KarierPoint.Near(hero, layout.KuliDrop, radius), deltaTime, CampaignTuning.Karier.KuliDropSeconds))
                    {
                        Carrying = false;
                        KuliDelivered++;
                        AddEnergi(-CampaignTuning.Karier.KuliEnergiPerSack);
                        if (KuliDelivered >= CampaignTuning.Karier.KuliSacks)
                            CompleteKuli();
                        else
                        {
                            Step = KarierStep.KuliAmbil;
                            Say("Sak " + KuliDelivered + "/" + CampaignTuning.Karier.KuliSacks + " beres. Ambil lagi di TUMPUKAN SEMEN.");
                            if (Energi <= 0)
                            {
                                Say("Badan remuk, ENERGI habis. Kerja kuli berhenti tanpa upah. REBAHAN atau MAKAN dulu.");
                                Cue(KarierCue.Gagal);
                                EndJob();
                            }
                        }
                    }
                    break;
                case KarierStep.BuzzerKetik:
                    if (Fill(KarierPoint.Near(hero, layout.Warkop, radius), deltaTime, CampaignTuning.Karier.BuzzerTypeSeconds))
                        CompleteBuzzer();
                    break;
                case KarierStep.ParkirJaga:
                    // Leaving the spot only pauses (motors wait), it does not reset.
                    if (!KarierPoint.Near(hero, layout.Parkir, radius))
                        break;
                    StepProgress += deltaTime / CampaignTuning.Karier.ParkirSecondsPerMotor;
                    if (StepProgress < 1f)
                        break;
                    StepProgress = 0f;
                    ParkirMotorsDone++;
                    Say(ParkirLines[(ParkirMotorsDone - 1) % ParkirLines.Length] + " (" + ParkirMotorsDone + "/" + CampaignTuning.Karier.ParkirMotors + ")");
                    Cue(KarierCue.Peluit);
                    if (ParkirMotorsDone >= CampaignTuning.Karier.ParkirMotors)
                        CompleteParkir();
                    break;
                case KarierStep.RondaKeliling:
                    if (RondaIndex < layout.RondaPoints.Length &&
                        Fill(KarierPoint.Near(hero, layout.RondaPoints[RondaIndex], radius), deltaTime, CampaignTuning.Karier.RondaCheckSeconds))
                    {
                        Say("Tok-tok-tok! " + RondaName(RondaIndex) + " aman. " + RondaLines[RondaIndex % RondaLines.Length]);
                        Cue(KarierCue.Notif);
                        RondaIndex++;
                        if (RondaIndex >= layout.RondaPoints.Length)
                        {
                            Step = KarierStep.RondaPulang;
                            Say("Keliling beres. Kembali ke POS RONDA, laporan ke Pak RT.");
                        }
                    }
                    else if (RondaIndex >= layout.RondaPoints.Length)
                        Step = KarierStep.RondaPulang;
                    break;
                case KarierStep.RondaPulang:
                    if (Fill(KarierPoint.Near(hero, layout.PosRt, radius), deltaTime, CampaignTuning.Karier.RondaCheckSeconds))
                        CompleteRonda();
                    break;
            }
        }

        private static readonly string[] ParkirLines =
        {
            "PRIIIT! \"Terus, terus, kiri... yak!\"  Motor keluar, Rp 2.000 masuk kantong.",
            "Pemotor: \"Tadi pas datang nggak ada tukang parkir, Mas!\"  Tetap bayar juga.",
            "PRIIIT! Kamu tahan jalan raya biar motor bisa keluar. Klakson bersahutan.",
            "Ibu-ibu kasih uang pas. Kamu bilang \"makasih, Bu\" sambil pura-pura sibuk.",
            "Pemotor kasih Rp 5.000: \"Kembaliannya ambil aja.\"  Rezeki anak soleh.",
            "PRIIIT! Motor terakhir keluar. Karcis? Karcis apa?"
        };

        private static readonly string[] RondaLines =
        {
            "Ada kucing guling-guling di tong sampah.", "Warkop masih ramai, bapak-bapak debat sepak bola.",
            "Taman sepi, cuma suara jangkrik dan nyamuk.", "Lampu jalan kedip-kedip, laporan ke kelurahan (lagi)."
        };

        private string RondaName(int index) =>
            index >= 0 && index < layout.RondaNames.Length ? layout.RondaNames[index] : "TITIK RONDA " + (index + 1);

        private void CompleteParkir()
        {
            int gross = ParkirMotorsDone * CampaignTuning.Karier.ParkirFee;
            int setoran = Round500(gross * CampaignTuning.Karier.ParkirSetoran);
            int net = gross - setoran;
            AddDuit(net);
            AddEnergi(-CampaignTuning.Karier.ParkirEnergi);
            AddRestu(CampaignTuning.Karier.ParkirRestu);
            ParkirCount++;
            Say("Setoran ke BOS PARKIR " + Rupiah(setoran) + " (\"uang keamanan\"). Bersih " + Rupiah(net) + ". RESTU " +
                CampaignTuning.Karier.ParkirRestu + ": warga tahu ini parkir liar.");
            Cue(KarierCue.Koin);
            EndJob();
        }

        private void CompleteRonda()
        {
            AddDuit(CampaignTuning.Karier.RondaPay);
            AddRestu(CampaignTuning.Karier.RondaRestu);
            AddEnergi(-CampaignTuning.Karier.RondaEnergi);
            RondaCount++;
            Say("Ronda selesai. Pak RT: \"Kampung aman, terima kasih.\"  Iuran ronda " + Rupiah(CampaignTuning.Karier.RondaPay) +
                ", RESTU +" + CampaignTuning.Karier.RondaRestu + ".");
            Cue(KarierCue.Koin);
            EndJob();
        }

        // Standing in the zone fills the step; leaving resets it. True once full.
        private bool Fill(bool inside, float deltaTime, float seconds)
        {
            if (!inside)
            {
                StepProgress = 0f;
                return false;
            }
            StepProgress += deltaTime / Math.Max(0.05f, seconds);
            if (StepProgress < 1f)
                return false;
            StepProgress = 0f;
            return true;
        }

        private void TickKeributan(float deltaTime, bool fighting)
        {
            if (PoliceCalled)
                return;
            // 0.6.1: once warga shouted, someone always calls the police; they come late,
            // even when the fight is already over (owner: the police must not skip a fight).
            if (Shouted && PoliceEta < 0f)
                PoliceEta = CampaignTuning.Karier.PolisiDatangSeconds;
            if (PoliceEta > 0f)
            {
                PoliceEta -= deltaTime;
                if (PoliceEta <= 0f)
                {
                    CallPolice(KarierPoliceReason.Keributan);
                    return;
                }
            }
            if (CalmLeft > 0f)
            {
                CalmLeft = Math.Max(0f, CalmLeft - deltaTime);
                return;
            }
            if (fighting)
            {
                Keributan = Math.Min(1f, Keributan + deltaTime / CampaignTuning.Karier.KeributanFillSeconds);
                energiCarry += CampaignTuning.Karier.FightEnergiPerSecond * deltaTime;
                if (energiCarry >= 1f)
                {
                    int lost = (int)energiCarry;
                    energiCarry -= lost;
                    AddEnergi(-lost);
                }
                if (!Shouted && Keributan >= CampaignTuning.Karier.TeriakAt)
                {
                    Shouted = true;
                    Say("Warga teriak: \"WOI! ADA YANG BERANTEM!\"  Tetangga berdatangan, HP merekam, ada yang telepon polisi.");
                    Cue(KarierCue.Teriak);
                }
                if (!MeleraiDone && Keributan >= CampaignTuning.Karier.MeleraiAt)
                {
                    MeleraiDone = true;
                    CalmLeft = CampaignTuning.Karier.MeleraiSeconds;
                    Say("Pak RT melerai: \"Sudah, sudah! Malu sama tetangga!\"  Kalau masih ribut, polisi dipanggil.");
                    Cue(KarierCue.Melerai);
                }
                if (Keributan >= 1f)
                    CallPolice(KarierPoliceReason.Keributan);
            }
            else if (Keributan > 0f)
            {
                Keributan = Math.Max(0f, Keributan - deltaTime / CampaignTuning.Karier.KeributanDecaySeconds);
                if (Keributan <= 0f && PoliceEta < 0f)
                    Shouted = MeleraiDone = false;
            }
        }

        // --- Jobs -------------------------------------------------------------------------

        public bool TakeJob(KarierJob job, out string reason)
        {
            reason = null;
            if (job == KarierJob.None)
                reason = "Pilih pekerjaan dulu.";
            else if (Busy)
                reason = "Selesaikan atau batalkan kerja yang sekarang dulu.";
            else if (Rebahan)
                reason = "Masih rebahan.";
            else if (PoliceCalled)
                reason = "Urusan dengan polisi belum selesai.";
            else if (InJail)
                reason = "Masih di dalam sel.";
            else if (job == KarierJob.Ojol && Energi < CampaignTuning.Karier.OjolEnergi)
                reason = "ENERGI habis. REBAHAN atau MAKAN dulu.";
            else if (job == KarierJob.Kuli && Energi < CampaignTuning.Karier.KuliEnergiPerSack * 2)
                reason = "Terlalu lemas untuk angkat semen. REBAHAN atau MAKAN dulu.";
            else if (job == KarierJob.Buzzer && BuzzerCooldown > 0f)
                reason = "Juragan buzzer belum kirim order. Tunggu " + (int)Math.Ceiling(BuzzerCooldown) + " detik.";
            else if (Tidur)
                reason = "Sedang tidur.";
            else if (TabrakPending)
                reason = "Urus dulu warga yang kamu tabrak.";
            else if (!OpenNow(Clock, job, out string closed))
                reason = closed;
            else if (job == KarierJob.Parkir && Energi < CampaignTuning.Karier.ParkirEnergi)
                reason = "ENERGI habis. REBAHAN atau MAKAN dulu.";
            else if (job == KarierJob.Ronda && Energi < CampaignTuning.Karier.RondaEnergi)
                reason = "Terlalu ngantuk untuk ronda. MAKAN dulu.";
            else if (job == KarierJob.Ronda && layout.RondaPoints.Length == 0)
                reason = "Belum ada jadwal ronda.";
            else if (job == KarierJob.Ojol && !NewOjolOrder())
                reason = "Belum ada order di sekitar.";
            if (reason != null)
                return false;

            if (Ride != KarierRide.None)
            {
                Say((Ride == KarierRide.Motor ? "Motor sewaan" : "Sepeda sewaan") + " dikembalikan dulu.");
                Ride = KarierRide.None;
            }
            Job = job;
            StepProgress = 0f;
            switch (job)
            {
                case KarierJob.Ojol:
                    Step = KarierStep.OjolJemput;
                    Say("ORDER MASUK: jemput penumpang di " + PlaceName(OjolFrom) + ", antar ke " + PlaceName(OjolTo) + ".");
                    break;
                case KarierJob.Kuli:
                    Step = KarierStep.KuliAmbil;
                    KuliDelivered = 0;
                    Say("Mandor: \"Angkut " + CampaignTuning.Karier.KuliSacks + " sak semen dari TUMPUKAN ke PROYEK. Upah dibayar kalau beres.\"");
                    break;
                case KarierJob.Buzzer:
                    Step = KarierStep.BuzzerKetik;
                    Say("Juragan buzzer: \"Duduk di WARKOP, sebar pesan ini ke semua grup WA. Jangan tanya sumbernya.\"");
                    break;
                case KarierJob.Parkir:
                    Step = KarierStep.ParkirJaga;
                    ParkirMotorsDone = 0;
                    Say("Bos parkir: \"Jaga depan KANTOR KELURAHAN. Rompi oranye pakai, peluit jangan lupa. Setoran 40%.\"");
                    break;
                case KarierJob.Ronda:
                    Step = KarierStep.RondaKeliling;
                    RondaIndex = 0;
                    Say("Pak RT: \"Malam ini giliranmu ronda. Keliling: " + string.Join(", ", layout.RondaNames) +
                        ", lalu lapor ke POS RONDA.\"  Tok-tok-tok!");
                    break;
            }
            Cue(KarierCue.Notif);
            return true;
        }

        public void CancelJob()
        {
            if (!Busy)
                return;
            Say(Job == KarierJob.Kuli ? "Kerja kuli ditinggal. Mandor: \"Upah hangus, ya!\""
                : Job == KarierJob.Parkir && ParkirMotorsDone > 0 ? "Parkir ditinggal. Bos parkir ambil semua setoranmu."
                : Job == KarierJob.Ronda ? "Ronda ditinggal. Pak RT mencatat namamu di buku \"bolos ronda\"."
                : "Kerja dibatalkan.");
            EndJob();
        }

        private void EndJob()
        {
            Job = KarierJob.None;
            Step = KarierStep.None;
            StepProgress = 0f;
            Carrying = false;
            KuliDelivered = 0;
            OjolFrom = OjolTo = -1;
            ParkirMotorsDone = 0;
            RondaIndex = 0;
        }

        private bool NewOjolOrder()
        {
            int count = layout.Places.Length;
            if (count < 2)
                return false;
            for (int attempt = 0; attempt < 24; attempt++)
            {
                int from = random.Next(count);
                int to = random.Next(count);
                if (from == to || KarierPoint.Distance(layout.Places[from], layout.Places[to]) < CampaignTuning.Karier.OjolMinTrip)
                    continue;
                OjolFrom = from;
                OjolTo = to;
                return true;
            }
            OjolFrom = 0;
            OjolTo = count - 1;
            return true;
        }

        public static int OjolGrossFare(float meters) =>
            Round500(CampaignTuning.Karier.OjolBaseFare + CampaignTuning.Karier.OjolFarePerMeter * Math.Max(0f, meters));

        private void CompleteOjol()
        {
            float distance = KarierPoint.Distance(Place(OjolFrom), Place(OjolTo));
            int gross = OjolGrossFare(distance);
            bool night = Night;
            if (night)
                gross = Round500(gross * (1f + CampaignTuning.Karier.OjolNightBonus));
            int cut = Round500(gross * CampaignTuning.Karier.OjolAppCut);
            int net = gross - cut;
            bool late = OjolTimeLeft < 0f;
            if (late)
                net = Round500(net * 0.5f);
            AddDuit(net);
            AddEnergi(-CampaignTuning.Karier.OjolEnergi);
            TripsOjol++;
            if (!late)
                AddRestu(CampaignTuning.Karier.OjolRestuOnTime);
            Say((late ? "TELAT! Penumpang kasih bintang 1, tarif dipotong separuh. " : "Sampai tepat waktu, bintang 5! ") +
                (night ? "Tarif malam " : "Tarif ") + Rupiah(gross) + " - potongan aplikasi " + Rupiah(cut) + (late ? " - denda telat" : string.Empty) +
                " = " + Rupiah(net) + ".");
            Cue(KarierCue.Koin);

            StepProgress = 0f;
            if (Energi < CampaignTuning.Karier.OjolEnergi)
            {
                Say("Lemas. Aplikasi ojol dimatikan dulu. REBAHAN atau MAKAN.");
                EndJob();
                return;
            }
            NewOjolOrder();
            Step = KarierStep.OjolJemput;
            Say("Order baru: jemput di " + PlaceName(OjolFrom) + " (buka HP untuk berhenti narik).");
        }

        private void CompleteKuli()
        {
            int net = CampaignTuning.Karier.KuliWage - CampaignTuning.Karier.KuliMandorCut;
            AddDuit(net);
            AddRestu(CampaignTuning.Karier.KuliRestu);
            SetKuli++;
            Say("UPAH KULI " + Rupiah(CampaignTuning.Karier.KuliWage) + " - uang rokok mandor " +
                Rupiah(CampaignTuning.Karier.KuliMandorCut) + " = " + Rupiah(net) + ". Kerja keras, hasil pas-pasan.");
            Cue(KarierCue.Koin);
            EndJob();
        }

        private static readonly string[] Hoaks =
        {
            "\"VIRAL! Air rebusan sandal jepit bikin kebal tilang\" terkirim ke 37 grup WA.",
            "\"Besok listrik padam seminggu, borong lilin sekarang!\" (sumber: katanya).",
            "\"Bansos cair hari ini, klik tautan ini\"  ...tautannya ternyata iklan pinjol.",
            "\"Makan mi instan pakai nasi bikin pintar\" dibagikan grup keluarga, 2.000 kali.",
            "\"Jalan kampung sudah diaspal\" lengkap dengan foto jalan negara tetangga."
        };

        private void CompleteBuzzer()
        {
            AddDuit(CampaignTuning.Karier.BuzzerPay);
            AddCatatan(CampaignTuning.Karier.BuzzerCatatan);
            AddRestu(CampaignTuning.Karier.BuzzerRestu);
            AddEnergi(-CampaignTuning.Karier.BuzzerEnergi);
            BuzzerCooldown = CampaignTuning.Karier.BuzzerCooldownSeconds;
            PostBuzzer++;
            Say(Hoaks[random.Next(Hoaks.Length)] + "  Bayaran " + Rupiah(CampaignTuning.Karier.BuzzerPay) +
                " masuk. CATATAN HITAM +" + CampaignTuning.Karier.BuzzerCatatan + ".");
            Cue(KarierCue.Koin);
            EndJob();

            // PASAL KARET: the higher the record, the likelier a report.
            if (CatatanHitam >= CampaignTuning.Karier.PasalKaretFrom)
            {
                double chance = (CatatanHitam - 40) / 100.0;
                if (random.NextDouble() < chance)
                    CallPolice(KarierPoliceReason.Hoaks);
            }
        }

        // --- Contextual actions -----------------------------------------------------------

        public KarierAction ActionAt(KarierPoint hero, out int sapaIndex)
        {
            sapaIndex = -1;
            if (Rebahan || PoliceCalled || InJail || Tidur || TabrakPending)
                return KarierAction.None;
            float radius = CampaignTuning.Karier.ZoneRadius;
            if (CanDaftar && KarierPoint.Near(hero, layout.PosRt, radius))
                return KarierAction.DaftarRT;
            for (int i = 0; i < layout.SapaPoints.Length; i++)
            {
                if (!Sapa(i) && KarierPoint.Near(hero, layout.SapaPoints[i], radius))
                {
                    sapaIndex = i;
                    return KarierAction.Sapa;
                }
            }
            if (Step != KarierStep.BuzzerKetik && KarierPoint.Near(hero, layout.Warkop, radius))
                return KarierAction.Makan;
            if (KarierPoint.Near(hero, layout.Siomay, radius))
                return KarierAction.BeliSiomay;
            if (KarierPoint.Near(hero, layout.Salome, radius))
                return KarierAction.BeliSalome;
            if (KarierPoint.Near(hero, layout.Bakso, radius))
                return KarierAction.BeliBakso;
            if (Ride == KarierRide.None && !Busy)
            {
                if (KarierPoint.Near(hero, layout.SewaSepeda, radius))
                    return KarierAction.SewaSepeda;
                if (KarierPoint.Near(hero, layout.SewaMotor, radius))
                    return KarierAction.SewaMotor;
            }
            if (Ride != KarierRide.None)
                return KarierAction.Turun;
            return KarierAction.None;
        }

        private static readonly string[] SapaLines =
        {
            "Bapak-bapak pos ronda: \"Jalan kampung bolong tiga tahun, Mas/Mbak.\"  Kamu dengarkan sampai habis kopi. RESTU +",
            "Ibu-ibu tukang sayur: \"Cabai naik lagi, gaji suami segitu-gitu aja.\"  Kamu ikut ngerumpi. RESTU +",
            "Driver ojol: \"Potongan aplikasi makin gede, bensin makin mahal.\"  Kamu kasih semangat. RESTU +"
        };

        public bool DoAction(KarierAction action, int sapaIndex)
        {
            switch (action)
            {
                case KarierAction.Makan:
                    return Eat("Nasi telur + es teh di warkop", CampaignTuning.Karier.MakanPrice, CampaignTuning.Karier.MakanEnergi);
                case KarierAction.BeliSiomay:
                    return Eat("Siomay bumbu kacang, pedasnya bikin melek", CampaignTuning.Karier.SiomayPrice, CampaignTuning.Karier.SiomayEnergi);
                case KarierAction.BeliSalome:
                    return Eat("Salome tusuk tiga, saus sambal banjir", CampaignTuning.Karier.SalomePrice, CampaignTuning.Karier.SalomeEnergi);
                case KarierAction.BeliBakso:
                    return Eat("Bakso urat semangkuk, ting-ting-ting", CampaignTuning.Karier.BaksoPrice, CampaignTuning.Karier.BaksoEnergi);
                case KarierAction.SewaSepeda:
                    return Rent(KarierRide.Sepeda, CampaignTuning.Karier.SewaSepedaPrice);
                case KarierAction.SewaMotor:
                    return Rent(KarierRide.Motor, CampaignTuning.Karier.SewaMotorPrice);
                case KarierAction.Turun:
                    if (Ride == KarierRide.None)
                        return false;
                    Say((Ride == KarierRide.Motor ? "Motor sewaan" : "Sepeda sewaan") + " dikembalikan. Jalan kaki lagi.");
                    Ride = KarierRide.None;
                    Cue(KarierCue.Notif);
                    return true;
                case KarierAction.Sapa:
                    if (sapaIndex < 0 || sapaIndex >= layout.SapaPoints.Length || Sapa(sapaIndex))
                        return false;
                    SapaMask |= 1 << sapaIndex;
                    AddRestu(CampaignTuning.Karier.SapaRestu);
                    Say(SapaLines[sapaIndex % SapaLines.Length] + CampaignTuning.Karier.SapaRestu);
                    Cue(KarierCue.Restu);
                    return true;
                case KarierAction.DaftarRT:
                    if (!CanDaftar)
                        return false;
                    AddDuit(-CampaignTuning.Karier.SyukuranRT);
                    Registered = true;
                    Say("Resmi DAFTAR CALON KETUA RT 03! Syukuran nasi kotak " + Rupiah(CampaignTuning.Karier.SyukuranRT) + " ludes.");
                    Cue(KarierCue.Daftar);
                    return true;
            }
            return false;
        }

        private bool Eat(string food, int price, int energi)
        {
            if (Eating)
                return false;
            if (Energi >= CampaignTuning.Karier.EnergiMax)
            {
                Say("Masih kenyang. ENERGI sudah penuh.");
                return false;
            }
            if (Duit < price)
            {
                Say("Duit kurang buat jajan. Penjual: \"Bon kemarin aja belum lunas!\"");
                Cue(KarierCue.Gagal);
                return false;
            }
            AddDuit(-price);
            AddEnergi(energi);
            FoodBought++;
            EatLeft = CampaignTuning.Karier.EatSeconds;
            Say(food + ". " + Rupiah(price) + ", ENERGI +" + energi + ".");
            Cue(KarierCue.Koin);
            return true;
        }

        private bool Rent(KarierRide ride, int price)
        {
            if (Ride != KarierRide.None || Busy)
                return false;
            if (Duit < price)
            {
                Say("Duit kurang buat sewa. Pemilik: \"KTP-nya ditinggal juga nggak cukup, Mas.\"");
                Cue(KarierCue.Gagal);
                return false;
            }
            AddDuit(-price);
            Ride = ride;
            RideCount++;
            Say(ride == KarierRide.Motor
                ? "Sewa motor " + Rupiah(price) + ". Helm? \"Deket kok, nggak usah.\"  Tekan TURUN untuk mengembalikan."
                : "Sewa sepeda " + Rupiah(price) + ". Kring-kring! Tekan TURUN untuk mengembalikan.");
            Cue(KarierCue.Notif);
            return true;
        }

        public bool StartRebahan(out string reason)
        {
            reason = null;
            if (Rebahan)
                reason = "Sudah rebahan.";
            else if (Tidur)
                reason = "Sedang tidur.";
            else if (TabrakPending)
                reason = "Urus dulu warga yang kamu tabrak.";
            else if (Busy)
                reason = "Lagi kerja. Batalkan dulu kalau mau rebahan.";
            else if (PoliceCalled || PoliceEta >= 0f)
                reason = "Polisi sedang menuju ke sini!";
            else if (InJail)
                reason = "Di sel cuma bisa duduk.";
            else if (Keributan > 0f)
                reason = "Masih ribut, mana bisa rebahan.";
            else if (Energi >= CampaignTuning.Karier.EnergiMax)
                reason = "ENERGI masih penuh. Rebahan terus nanti jadi kaum rebahan sejati.";
            if (reason != null)
                return false;
            Ride = KarierRide.None;
            RebahanLeft = CampaignTuning.Karier.RebahanSeconds;
            RebahanCount++;
            Say("Rebahan sambil scroll sosmed...");
            return true;
        }

        // --- Fights, police ---------------------------------------------------------------

        public void OnPremanBeaten(int count)
        {
            if (count <= 0)
                return;
            PremanBeaten += count;
            if (Shouted || Keributan > 0f || PoliceEta >= 0f)
                BeatenThisFight = true;
            AddRestu(CampaignTuning.Karier.PremanRestu * count);
            AddDuit(CampaignTuning.Karier.PremanTip);
            Say("Pemalak kabur! Tukang sayur kasih " + Rupiah(CampaignTuning.Karier.PremanTip) +
                " tanda terima kasih. RESTU +" + CampaignTuning.Karier.PremanRestu * count + ".");
            Cue(KarierCue.Restu);
        }

        public void OnHeroRuntuh()
        {
            int pay = Math.Min(Duit, CampaignTuning.Karier.PingsanBiaya);
            AddDuit(-pay);
            Energi = Math.Min(Energi, CampaignTuning.Karier.PingsanEnergi);
            EndJob();
            Ride = KarierRide.None;
            Keributan = 0f;
            Shouted = MeleraiDone = false;
            CalmLeft = 0f;
            PoliceEta = -1f;
            BeatenThisFight = false;
            TabrakPending = false;
            Chasing = false;
            if (PoliceCalled && !PoliceArrived)
                PoliceReason = KarierPoliceReason.None;
            Say("Pingsan dihajar preman. Warga gotong ke puskesmas, biaya " + Rupiah(pay) + ".");
            Cue(KarierCue.Gagal);
        }

        public void CallPolice(KarierPoliceReason reason)
        {
            if (PoliceCalled || reason == KarierPoliceReason.None)
                return;
            PoliceReason = reason;
            PoliceArrived = false;
            PoliceEta = -1f;
            Keributan = 1f;
            CalmLeft = 0f;
            Say(reason == KarierPoliceReason.Hoaks
                ? "Postinganmu viral dan dilaporkan! Polisi datang menjemput: PASAL KARET."
                : "Sirene mendekat! Polisi akhirnya datang (seperti biasa, setelah semuanya selesai).");
            Cue(KarierCue.Sirene);
        }

        public void PoliceArrive()
        {
            if (PoliceCalled)
                PoliceArrived = true;
        }

        public int DamaiPrice => PoliceReason == KarierPoliceReason.Hoaks
            ? CampaignTuning.Karier.DamaiHoaks + CatatanHitam * CampaignTuning.Karier.DamaiHoaksPerCatatan
            : PoliceReason == KarierPoliceReason.TabrakLari
            ? CampaignTuning.Karier.DamaiTabrak + CatatanHitam * CampaignTuning.Karier.DamaiTabrakPerCatatan
            : CampaignTuning.Karier.DamaiFight + CatatanHitam * CampaignTuning.Karier.DamaiFightPerCatatan;

        public bool CanDamai => Duit >= DamaiPrice;

        public bool ResolvePolice(KarierPoliceChoice choice)
        {
            if (!PoliceCalled || !PoliceArrived)
                return false;
            bool hoaks = PoliceReason == KarierPoliceReason.Hoaks;
            bool tabrak = PoliceReason == KarierPoliceReason.TabrakLari;
            switch (choice)
            {
                case KarierPoliceChoice.Kabur:
                    if (tabrak)
                        return false; // Already caught after running once.
                    AddCatatan(CampaignTuning.Karier.KaburCatatan);
                    AddRestu(CampaignTuning.Karier.KaburRestu);
                    Say("KABUR lewat gang tikus! Lolos, tapi wajahmu sudah terekam HP warga. CATATAN HITAM +" +
                        CampaignTuning.Karier.KaburCatatan + ".");
                    break;
                case KarierPoliceChoice.Damai:
                    int price = DamaiPrice;
                    if (Duit < price)
                    {
                        Say("Dompet tipis, \"damai\" ditolak.");
                        Cue(KarierCue.Gagal);
                        return false;
                    }
                    AddDuit(-price);
                    AddCatatan(CampaignTuning.Karier.DamaiCatatan);
                    Say("DAMAI DI TEMPAT " + Rupiah(price) + ". \"Ya sudah, hati-hati di jalan.\"  Tidak ada kuitansi.");
                    break;
                case KarierPoliceChoice.Saksi:
                    if (!CanSaksi)
                        return false;
                    AddRestu(CampaignTuning.Karier.SaksiRestuGain);
                    Say("Warga jadi saksi: \"Dia yang ngusir preman, Pak!\"  Polisi manggut-manggut... lalu minta foto bareng buat laporan.");
                    break;
                case KarierPoliceChoice.Polsek:
                    AddRestu(CampaignTuning.Karier.PolsekRestu);
                    AddEnergi(CampaignTuning.Karier.PolsekEnergi);
                    AddCatatan(hoaks || tabrak ? CampaignTuning.Karier.ArrestPolsekCatatan : CampaignTuning.Karier.PolsekCatatan);
                    if (tabrak)
                        Say("Motor diamankan sebagai barang bukti.");
                    Say("Tangan diborgol. \"Ikut kami ke POLSEK!\"  Ibu-ibu langsung kirim videonya ke grup.");
                    EndJob();
                    Ride = KarierRide.None;
                    break;
            }
            PoliceReason = KarierPoliceReason.None;
            PoliceArrived = false;
            PoliceEta = -1f;
            BeatenThisFight = false;
            Keributan = 0f;
            Shouted = MeleraiDone = false;
            CalmLeft = 0f;
            Chasing = false;
            if (tabrak)
                tabrakCooldown = CampaignTuning.Karier.TabrakCooldown;
            Cue(KarierCue.Notif);
            return true;
        }

        // The hero sits in the POLSEK cell (after the arrest ride).
        public void EnterJail()
        {
            JailLeft = CampaignTuning.Karier.JailSeconds;
            Say("Masuk sel POLSEK KONOHA. Tunggu " + (int)CampaignTuning.Karier.JailSeconds +
                " detik, atau TEBUS " + Rupiah(TebusPrice) + " (tanpa kuitansi).");
        }

        public bool Tebus()
        {
            if (!InJail)
                return false;
            int price = TebusPrice;
            if (Duit < price)
            {
                Say("Duit tidak cukup untuk \"uang jaminan\". Silakan menikmati sel.");
                Cue(KarierCue.Gagal);
                return false;
            }
            AddDuit(-price);
            JailLeft = 0f;
            Say("Uang jaminan " + Rupiah(price) + " diterima. Pintu sel tiba-tiba terbuka.");
            Cue(KarierCue.Koin);
            return true;
        }

        // --- Missions (0.6.2): a guided chain, every step says what to do and where -------
        // Owner (0.6.1): "banyak momen aku bingung mau ngapain". Each mission has steps with
        // an instruction, a place for the arrow (or the HP button to press), and a check.

        public const int MisiPreman = 6;
        public const int MisiTawaran = 7;

        public static readonly string[] MissionTitles =
        {
            "KENALAN PAK RT", "CARI KERJA", "JAJAN SIOMAY", "GOWES KE PLAZA", "KULI HARIAN", "KENALAN WARGA",
            "PAHLAWAN GANG", "TAWARAN GELAP", "ISTIRAHAT", "TABUNGAN", "RESTU WARGA", "DAFTAR CALON RT"
        };

        private static readonly string[] MissionIntro =
        {
            "Hari pertama di RT 03. Sapa PAK RT di POS RONDA dulu (ikuti panah kecil di tanah).",
            "Pak RT: \"Mau jadi Ketua RT? Syaratnya syukuran Rp 1 juta dan dipercaya warga. Kerja dulu!\"",
            "Perut keroncongan. Beli SIOMAY di gerobak dekat boulevard.",
            "Sewa SEPEDA di dekat gerbang, lalu gowes ke PLAZA.",
            "Mandor (WA): \"Butuh kuli hari ini, 5 sak semen.\"  Buka HP > KULI.",
            "Kenalan dengan ibu-ibu tukang sayur dan driver ojol.",
            "Warga (WA): \"Preman malak di mulut gang! Ada yang berani?\"",
            "Nomor tak dikenal (WA): \"Mau duit cepat? Sebar pesan ini ke grup. Rp 250rb langsung cair.\"",
            "Badan pegal. Buka HP > REBAHAN sebentar.",
            "Syukuran RT butuh modal. Kumpulkan tabungan " + Rupiah(CampaignTuning.Karier.MisiTabungan) + " (OJOL, KULI, atau... BUZZER).",
            "Pak Haji: \"Calon RT harus dipercaya warga.\"  Kumpulkan RESTU " + CampaignTuning.Karier.RestuSyaratRT + ".",
            "Kumpulkan " + Rupiah(CampaignTuning.Karier.SyukuranRT) + " untuk syukuran, lalu DAFTAR di POS RONDA."
        };

        public int RebahanCount { get; private set; }
        public bool RodeToPlaza { get; private set; }
        public bool AllMissionsDone => Mission >= MissionTitles.Length;
        public string MissionTitle => AllMissionsDone ? "TUGAS HARIAN" : MissionTitles[Mission];
        public string MissionIntroText => AllMissionsDone ? string.Empty : MissionIntro[Mission];

        // The current step of the current mission: what to do, where (arrow), or which button.
        public string MissionProgress => MissionStep(out _, out _, out _);

        // True when the step is done in the HP (KONOHA KERJA): the HP button blinks.
        public bool MissionNeedsPhone
        {
            get
            {
                MissionStep(out _, out _, out bool phone);
                return phone;
            }
        }

        public bool MissionTarget(out KarierPoint point, out string label)
        {
            MissionStep(out point, out label, out _);
            return label.Length > 0;
        }

        private string MissionStep(out KarierPoint point, out string label, out bool phone)
        {
            point = new KarierPoint(0f, 0f);
            label = string.Empty;
            phone = false;
            switch (Mission)
            {
                case 0:
                    point = layout.PosRt;
                    label = "PAK RT";
                    return "Sapa PAK RT di POS RONDA (tombol SAPA)";
                case 1:
                    if (Job == KarierJob.Ojol)
                        return "Antar 1 penumpang OJOL (ikuti panah)";
                    phone = true;
                    return "Tekan HP • KERJA, lalu pilih OJOL";
                case 2:
                    point = layout.Siomay;
                    label = "SIOMAY";
                    return "Beli SIOMAY di gerobak (tombol SIOMAY)";
                case 3:
                    if (Ride == KarierRide.None)
                    {
                        point = layout.SewaSepeda;
                        label = "SEWA SEPEDA";
                        return "Sewa SEPEDA di dekat gerbang";
                    }
                    point = layout.Plaza;
                    label = "PLAZA";
                    return "Gowes ke PLAZA";
                case 4:
                    if (Job == KarierJob.Kuli)
                        return "Angkut 5 sak: TUMPUKAN SEMEN > PROYEK";
                    if (!JobOpen(KarierJob.Kuli))
                    {
                        // 0.6.3: the project only hires 07.00-17.00.
                        phone = CanTidurNow && !Busy;
                        return CanTidurNow ? "Proyek tutup malam. HP > TIDUR, besok pagi KULI"
                            : "Proyek buka lagi jam 07.00. Kerja OJOL dulu sambil menunggu";
                    }
                    phone = true;
                    return "Tekan HP • KERJA, lalu pilih KULI";
                case 5:
                    for (int i = 0; i < layout.SapaPoints.Length; i++)
                        if (!Sapa(i))
                        {
                            point = layout.SapaPoints[i];
                            label = "SAPA " + (i < layout.SapaNames.Length ? layout.SapaNames[i] : "WARGA");
                            return "Sapa warga " + SapaCount + "/" + layout.SapaPoints.Length + " (ikuti panah)";
                        }
                    return "Sapa warga " + SapaCount + "/" + layout.SapaPoints.Length;
                case 6:
                    point = layout.PremanSpot;
                    label = "PREMAN";
                    return "Usir PREMAN di mulut gang (tombol pukul)";
                case 7:
                    return "Jawab WA nomor tak dikenal: TERIMA atau TOLAK";
                case 8:
                    if (Energi >= CampaignTuning.Karier.EnergiMax)
                        return "Energi masih penuh: kerja dulu, lalu REBAHAN";
                    phone = true;
                    return "Tekan HP • KERJA, lalu pilih REBAHAN";
                case 9:
                    if (!Busy)
                        phone = true;
                    return "Tabungan " + Rupiah(Duit) + " / " + Rupiah(CampaignTuning.Karier.MisiTabungan) + (Busy ? string.Empty : " • HP > kerja");
                case 10:
                    return "RESTU " + Restu + " / " + CampaignTuning.Karier.RestuSyaratRT + " • sapa, antar tepat waktu, usir preman";
                case 11:
                    if (Duit >= CampaignTuning.Karier.SyukuranRT)
                    {
                        point = layout.PosRt;
                        label = "DAFTAR RT";
                        return "DAFTAR di POS RONDA (tombol DAFTAR)";
                    }
                    if (!Busy)
                        phone = true;
                    return "Duit syukuran " + Rupiah(Duit) + " / " + Rupiah(CampaignTuning.Karier.SyukuranRT) + (Busy ? string.Empty : " • HP > kerja");
                default:
                    return TugasStep(out point, out label, out phone);
            }
        }

        private bool MissionDone(int index)
        {
            switch (index)
            {
                case 0: return Sapa(0);
                case 1: return TripsOjol > 0;
                case 2: return FoodBought > 0;
                case 3: return RodeToPlaza;
                case 4: return SetKuli > 0;
                case 5: return SapaCount >= layout.SapaPoints.Length;
                case 6: return PremanBeaten > 0;
                case 7: return false; // Answered through AnswerOffer.
                case 8: return RebahanCount > 0;
                case 9: return Duit >= CampaignTuning.Karier.MisiTabungan || Registered;
                case 10: return Restu >= CampaignTuning.Karier.RestuSyaratRT;
                case 11: return Registered;
                default: return false;
            }
        }

        private void CheckMission()
        {
            // Gowes ke plaza: arriving there on a rented bike or motor.
            if (!RodeToPlaza && Ride != KarierRide.None && lastHero.HasValue &&
                KarierPoint.Near(lastHero.Value, layout.Plaza, CampaignTuning.Karier.ZoneRadius * 1.5f))
                RodeToPlaza = true;
            // Several can finish at once (e.g. a loaded save); one per tick keeps messages readable.
            if (!AllMissionsDone && MissionDone(Mission))
                CompleteMission();
        }

        private void CompleteMission()
        {
            int done = Mission;
            switch (done)
            {
                case 1: AddDuit(CampaignTuning.Karier.MisiKerjaReward); break;
                case 3: AddRestu(2); break;
                case 5: AddRestu(CampaignTuning.Karier.SapaRestu); break;
                case 9: AddRestu(3); break;
            }
            Mission++;
            Say("MISI SELESAI: " + MissionTitles[done] + (done == 1 ? " (+" + Rupiah(CampaignTuning.Karier.MisiKerjaReward) + ")" : string.Empty) + ".");
            if (!AllMissionsDone)
                Say("MISI " + (Mission + 1) + ": " + MissionTitles[Mission] + ". " + MissionIntro[Mission]);
            else if (!celebrationSeen)
                CelebrationPending = true;
            Cue(KarierCue.Misi);
        }

        // TAWARAN GELAP: accept (fast money, record) or refuse (restu).
        public bool AnswerOffer(bool accept)
        {
            if (!OfferPending)
                return false;
            if (accept)
            {
                AddDuit(CampaignTuning.Karier.TawaranPay);
                AddCatatan(CampaignTuning.Karier.TawaranCatatan);
                AddRestu(-2);
                PostBuzzer++;
                Say("Pesan diteruskan ke 12 grup. " + Rupiah(CampaignTuning.Karier.TawaranPay) + " masuk. CATATAN HITAM +" +
                    CampaignTuning.Karier.TawaranCatatan + ". Nomor itu lalu hilang.");
            }
            else
            {
                AddRestu(CampaignTuning.Karier.TolakRestu);
                Say("Kamu blokir nomornya dan lapor ke grup RT. Pak RT: \"Mantap, hati-hati penipuan!\" RESTU +" +
                    CampaignTuning.Karier.TolakRestu + ".");
            }
            CompleteMission();
            return true;
        }

        // --- 0.6.3 TUGAS HARIAN: three small tasks every day after the missions ---------------
        // Owner (0.6.2): after the last mission "aku bingung harus ngapain lagi". Every day has
        // three tasks with an arrow or the blinking HP, a small reward each and a bonus for all.

        public const int TugasCount = 3;

        public KarierTugas TugasKind(int index)
        {
            switch (index)
            {
                case 0: return KarierTugas.Ojol;
                case 1: return Day % 2 == 0 ? KarierTugas.Kuli : KarierTugas.Parkir;
                default: return Day % 2 == 0 ? KarierTugas.Jajan : KarierTugas.Ronda;
            }
        }

        public int TugasNeed(int index)
        {
            switch (TugasKind(index))
            {
                case KarierTugas.Ojol: return 2;
                case KarierTugas.Jajan: return 2;
                default: return 1;
            }
        }

        private int TugasCounter(KarierTugas kind)
        {
            switch (kind)
            {
                case KarierTugas.Ojol: return TripsOjol;
                case KarierTugas.Kuli: return SetKuli;
                case KarierTugas.Parkir: return ParkirCount;
                case KarierTugas.Ronda: return RondaCount;
                default: return FoodBought;
            }
        }

        public int TugasProgress(int index)
        {
            if (index < 0 || index >= TugasCount)
                return 0;
            if (TugasDay != Day)
                return 0;
            int done = TugasCounter(TugasKind(index)) - tugasBase[index];
            return Math.Max(0, Math.Min(TugasNeed(index), done));
        }

        public bool TugasDone(int index) => (TugasMask & (1 << index)) != 0;

        public bool AllTugasDone => TugasDay == Day && TugasMask == (1 << TugasCount) - 1;

        public string TugasName(int index)
        {
            int need = TugasNeed(index);
            switch (TugasKind(index))
            {
                case KarierTugas.Ojol: return "Antar " + need + " penumpang OJOL";
                case KarierTugas.Kuli: return "Kerja KULI 1x (07.00-17.00)";
                case KarierTugas.Parkir: return "Jaga PARKIR 1x (08.00-21.00)";
                case KarierTugas.Ronda: return "RONDA MALAM (21.00-03.00)";
                default: return "Jajan " + need + "x (siomay, salome, bakso)";
            }
        }

        private void EnsureTugas()
        {
            if (TugasDay == Day)
                return;
            TugasDay = Day;
            TugasMask = 0;
            for (int i = 0; i < TugasCount; i++)
                tugasBase[i] = TugasCounter(TugasKind(i));
        }

        private void CheckTugas()
        {
            if (!AllMissionsDone)
                return;
            EnsureTugas();
            for (int i = 0; i < TugasCount; i++)
            {
                if (TugasDone(i) || TugasProgress(i) < TugasNeed(i))
                    continue;
                TugasMask |= 1 << i;
                AddDuit(CampaignTuning.Karier.TugasReward);
                AddRestu(CampaignTuning.Karier.TugasRestu);
                Say("TUGAS HARIAN BERES: " + TugasName(i) + " (+" + Rupiah(CampaignTuning.Karier.TugasReward) + ").");
                if (AllTugasDone)
                {
                    AddDuit(CampaignTuning.Karier.TugasBonus);
                    Say("SEMUA TUGAS HARI KE-" + Day + " BERES! Bonus " + Rupiah(CampaignTuning.Karier.TugasBonus) +
                        ". Kerja bebas cari tabungan, atau TIDUR (mulai 19.00) untuk hari berikutnya.");
                }
                Cue(KarierCue.Misi);
                return; // One per tick keeps the messages readable.
            }
        }

        private string TugasStep(out KarierPoint point, out string label, out bool phone)
        {
            point = new KarierPoint(0f, 0f);
            label = string.Empty;
            phone = false;
            if (TugasDay != Day)
                return "Tugas harian baru sedang disiapkan...";
            for (int i = 0; i < TugasCount; i++)
            {
                if (TugasDone(i))
                    continue;
                KarierTugas kind = TugasKind(i);
                string progress = " " + TugasProgress(i) + "/" + TugasNeed(i);
                switch (kind)
                {
                    case KarierTugas.Jajan:
                        point = layout.Siomay;
                        label = "JAJAN";
                        return TugasName(i) + progress + " (ikuti panah)";
                    case KarierTugas.Kuli:
                    case KarierTugas.Parkir:
                    case KarierTugas.Ronda:
                        KarierJob job = kind == KarierTugas.Kuli ? KarierJob.Kuli : kind == KarierTugas.Parkir ? KarierJob.Parkir : KarierJob.Ronda;
                        if (!JobOpen(job) && Job != job)
                        {
                            // Not open now: another task first, or wait / TIDUR.
                            bool other = false;
                            for (int k = 0; k < TugasCount; k++)
                                if (k != i && !TugasDone(k) && TaskOpenNow(k)) other = true;
                            if (other)
                                continue;
                            return TugasName(i) + " • belum buka, kerja bebas dulu" +
                                (kind == KarierTugas.Ronda ? string.Empty : " atau TIDUR malam ini");
                        }
                        break;
                }
                if (!Busy)
                    phone = true;
                return TugasName(i) + progress + (Busy ? string.Empty : " • HP > kerja");
            }
            return "Tugas hari ke-" + Day + " beres! Kerja bebas, atau TIDUR (19.00-04.00) lewat HP";
        }

        private bool TaskOpenNow(int index)
        {
            switch (TugasKind(index))
            {
                case KarierTugas.Kuli: return JobOpen(KarierJob.Kuli);
                case KarierTugas.Parkir: return JobOpen(KarierJob.Parkir);
                case KarierTugas.Ronda: return JobOpen(KarierJob.Ronda);
                default: return true;
            }
        }

        // The congratulations panel was shown (KarierController).
        public void AckCelebration()
        {
            CelebrationPending = false;
            celebrationSeen = true;
            EnsureTugas();
        }

        // --- Helpers ------------------------------------------------------------------------

        public KarierPoint Place(int index) =>
            index >= 0 && index < layout.Places.Length ? layout.Places[index] : new KarierPoint(0f, 0f);

        public string PlaceName(int index) =>
            index >= 0 && index < layout.PlaceNames.Length ? layout.PlaceNames[index] : "TUJUAN";

        // Where the current step wants the hero; false when nothing is pending.
        public bool Target(out KarierPoint point, out string label)
        {
            switch (Step)
            {
                case KarierStep.OjolJemput: point = Place(OjolFrom); label = "JEMPUT: " + PlaceName(OjolFrom); return true;
                case KarierStep.OjolAntar: point = Place(OjolTo); label = "ANTAR: " + PlaceName(OjolTo); return true;
                case KarierStep.KuliAmbil: point = layout.KuliPickup; label = "TUMPUKAN SEMEN"; return true;
                case KarierStep.KuliAntar: point = layout.KuliDrop; label = "PROYEK"; return true;
                case KarierStep.BuzzerKetik: point = layout.Warkop; label = "WARKOP"; return true;
                case KarierStep.ParkirJaga: point = layout.Parkir; label = "PARKIR: KANTOR KELURAHAN"; return true;
                case KarierStep.RondaKeliling:
                    if (RondaIndex < layout.RondaPoints.Length)
                    {
                        point = layout.RondaPoints[RondaIndex];
                        label = "RONDA: " + RondaName(RondaIndex);
                        return true;
                    }
                    point = layout.PosRt; label = "RONDA: POS RONDA"; return true;
                case KarierStep.RondaPulang: point = layout.PosRt; label = "RONDA: POS RONDA"; return true;
            }
            if (TabrakPending)
            {
                point = TabrakAt;
                label = "KORBAN TABRAKAN";
                return true;
            }
            if (Chasing)
            {
                point = new KarierPoint(0f, 0f);
                label = string.Empty;
                return false;
            }
            if (CanDaftar)
            {
                point = layout.PosRt;
                label = "DAFTAR RT: POS RONDA";
                return true;
            }
            // 0.6.2: the current mission points the way when no job runs.
            if (!InJail && !PoliceCalled && MissionTarget(out point, out label))
                return true;
            point = new KarierPoint(0f, 0f);
            label = string.Empty;
            return false;
        }

        public void AddDuit(int amount) => Duit = Math.Max(0, Duit + amount);
        public void AddEnergi(int amount) => Energi = Clamp(Energi + amount, 0, CampaignTuning.Karier.EnergiMax);
        public void AddRestu(int amount) => Restu = Clamp(Restu + amount, 0, CampaignTuning.Karier.RestuMax);
        public void AddCatatan(int amount) => CatatanHitam = Clamp(CatatanHitam + amount, 0, CampaignTuning.Karier.CatatanMax);

        private static int Clamp(int value, int min, int max) => value < min ? min : value > max ? max : value;

        public static int Round500(float value) => (int)Math.Round(value / 500.0, MidpointRounding.AwayFromZero) * 500;

        // "Rp 1.250.000" (Indonesian thousands separator).
        public static string Rupiah(int value)
        {
            string digits = Math.Abs(value).ToString(CultureInfo.InvariantCulture);
            var builder = new StringBuilder(digits.Length + 6);
            for (int i = 0; i < digits.Length; i++)
            {
                if (i > 0 && (digits.Length - i) % 3 == 0)
                    builder.Append('.');
                builder.Append(digits[i]);
            }
            return (value < 0 ? "-Rp " : "Rp ") + builder;
        }

        private void Say(string message) => Notified?.Invoke(message);
        private void Cue(KarierCue cue) => Cued?.Invoke(cue);

        // --- Save (PlayerPrefs on the tablet) ----------------------------------------------

        public string Serialize()
        {
            return string.Join(";", new[]
            {
                "K4", Duit.ToString(CultureInfo.InvariantCulture), Energi.ToString(CultureInfo.InvariantCulture),
                Restu.ToString(CultureInfo.InvariantCulture), CatatanHitam.ToString(CultureInfo.InvariantCulture),
                SapaMask.ToString(CultureInfo.InvariantCulture), Registered ? "1" : "0",
                TripsOjol.ToString(CultureInfo.InvariantCulture), SetKuli.ToString(CultureInfo.InvariantCulture),
                PostBuzzer.ToString(CultureInfo.InvariantCulture), PremanBeaten.ToString(CultureInfo.InvariantCulture),
                Mission.ToString(CultureInfo.InvariantCulture), FoodBought.ToString(CultureInfo.InvariantCulture),
                RideCount.ToString(CultureInfo.InvariantCulture), RebahanCount.ToString(CultureInfo.InvariantCulture),
                RodeToPlaza ? "1" : "0",
                // 0.6.3 (K4): day, clock, new jobs, daily tasks, congratulations seen.
                Day.ToString(CultureInfo.InvariantCulture), ((int)Clock).ToString(CultureInfo.InvariantCulture),
                ParkirCount.ToString(CultureInfo.InvariantCulture), RondaCount.ToString(CultureInfo.InvariantCulture),
                TabrakCount.ToString(CultureInfo.InvariantCulture), TugasDay.ToString(CultureInfo.InvariantCulture),
                tugasBase[0].ToString(CultureInfo.InvariantCulture), tugasBase[1].ToString(CultureInfo.InvariantCulture),
                tugasBase[2].ToString(CultureInfo.InvariantCulture), TugasMask.ToString(CultureInfo.InvariantCulture),
                celebrationSeen ? "1" : "0"
            });
        }

        public bool TryLoad(string text)
        {
            if (string.IsNullOrEmpty(text))
                return false;
            string[] parts = text.Split(';');
            // K1 = 0.6.0 save (no missions), K2 = 0.6.1.
            bool v1 = parts.Length == 11 && parts[0] == "K1";
            bool v2 = parts.Length == 14 && parts[0] == "K2";
            bool v3 = parts.Length == 16 && parts[0] == "K3";
            bool v4 = parts.Length == 27 && parts[0] == "K4";
            if (!v1 && !v2 && !v3 && !v4)
                return false;
            var values = new int[parts.Length - 1];
            for (int i = 0; i < values.Length; i++)
                if (!KarierAvatar.Int(parts[i + 1], out values[i]))
                    return false;
            ResetProgress();
            Duit = Math.Max(0, values[0]);
            Energi = Clamp(values[1], 0, CampaignTuning.Karier.EnergiMax);
            Restu = Clamp(values[2], 0, CampaignTuning.Karier.RestuMax);
            CatatanHitam = Clamp(values[3], 0, CampaignTuning.Karier.CatatanMax);
            SapaMask = Math.Max(0, values[4]);
            Registered = values[5] == 1;
            TripsOjol = Math.Max(0, values[6]);
            SetKuli = Math.Max(0, values[7]);
            PostBuzzer = Math.Max(0, values[8]);
            PremanBeaten = Math.Max(0, values[9]);
            if (v3 || v4)
            {
                RebahanCount = Math.Max(0, values[13]);
                RodeToPlaza = values[14] == 1;
            }
            if (v4)
            {
                Day = Math.Max(1, values[15]);
                Clock = Clamp(values[16], 0, 1439);
                ParkirCount = Math.Max(0, values[17]);
                RondaCount = Math.Max(0, values[18]);
                TabrakCount = Math.Max(0, values[19]);
                TugasDay = Math.Max(0, values[20]);
                tugasBase[0] = Math.Max(0, values[21]);
                tugasBase[1] = Math.Max(0, values[22]);
                tugasBase[2] = Math.Max(0, values[23]);
                TugasMask = Clamp(values[24], 0, (1 << TugasCount) - 1);
                celebrationSeen = values[25] == 1;
            }
            if (v2 || v3 || v4)
            {
                // 0.6.1 saves used another mission list: start the 0.6.2 chain again (done
                // missions finish themselves one per tick).
                Mission = v3 || v4 ? Clamp(values[10], 0, MissionTitles.Length) : 0;
                FoodBought = Math.Max(0, values[11]);
                RideCount = Math.Max(0, values[12]);
            }
            // A life that finished every mission before 0.6.3 still gets the congratulations.
            CelebrationPending = AllMissionsDone && !celebrationSeen;
            return true;
        }
    }
}
